#!/bin/bash

# TODO: handle cases when $wallpaper_image, $wallpaper_mode or $wallpaper_bg_color is not set by the theme

function init_module() {
    NITROGEN_ENABLE_DEFAULT="true"
    NITROGEN_ENABLE="$(crudini --get ${GCS_CONFIG_FILE} background-nitrogen enable 2>/dev/null || echo "${NITROGEN_ENABLE_DEFAULT}")"
}



function check_dependencies() {
    if ! which nitrogen >/dev/null; then
        return 1

    elif ! [ "${NITROGEN_ENABLE}" == "true" ]; then
        printf "* Ignoring wallpaper for nitrogen (disabled from configuration).\n"
        return 1

    else
        return 0

    fi
}



function derive_colors() {
    for i in ${COLOR_THEME_DIRS[@]}; do
        if [ -f "$i/${wallpaper_image}" ]; then
            wallpaper_file="$i/${wallpaper_image}"
        fi
    done
}



function create_backup() {
    printf "* Backup/restore not supported with nitrogen.\n"
}



function restore_backup() {
    printf "* Backup/restore not supported with nitrogen.\n"
}



function dry_run() {
    printf "* nitrogen: set desktop wallpaper on the X11 root window.\n"
}



function apply_theme() {
    if ! [ -f "${wallpaper_file}" ]; then
        printf "* Not setting wallpaper with nitrogen (image file not found: \"${wallpaper_image}\").\n"

    else
        printf "* Setting wallpaper with nitrogen..."
        case "${wallpaper_mode}" in
            centered)  nitrogen --save --set-centered "${wallpaper_file}" --set-color=${wallpaper_bg_color};;
            tiled)     nitrogen --save --set-tiled "${wallpaper_file}";;
            stretched) nitrogen --save --set-scaled "${wallpaper_file}";;
            zoom-fit)  nitrogen --save --set-zoom "${wallpaper_file}" --set-color=${wallpaper_bg_color};;
            zoom-fill) nitrogen --save --set-zoom-fill "${wallpaper_file}";;
        esac

        desktop_background_symlink="$HOME/.config/desktop-background"
        [ -e "${desktop_background_symlink}" ] && rm "${desktop_background_symlink}"
        ln -s "${wallpaper_file}" "${desktop_background_symlink}"

        printf " done.\n"

    fi
}

