#!/bin/bash
# TODO: handle cases when $wallpaper_image, $wallpaper_mode or $wallpaper_bg_color is not set by the theme

function init_module() {
    BACKGROUND_PCMANFM_ENABLE_DEFAULT="true"
    BACKGROUND_PCMANFM_ENABLE="$(crudini --get ${GCS_CONFIG_FILE} background-pcmanfm enable 2>/dev/null || echo "${BACKGROUND_PCMANFM_ENABLE_DEFAULT}")"
}



function check_dependencies() {
    if ! which -s pcmanfm; then
        return 1

    elif ! which -s pgrep; then
        return 1

    elif ! [ "${BACKGROUND_PCMANFM_ENABLE}" == "true" ]; then
        printf "* Ignoring wallpaper for PCManFM (disabled from configuration).\n"
        return 1

    else
        return 0

    fi

}



function derive_colors() {
    for color_theme_dir in ${COLOR_THEME_DIRS[@]}; do
        if [ -f "${color_theme_dir}/${wallpaper_image}" ]; then
            wallpaper_file="${color_theme_dir}/${wallpaper_image}"
        fi
    done
}



function create_backup() {
    printf "* Backup/restore not supported with PCManFM wallpaper.\n"
}



function restore_backup() {
    printf "* Backup/restore not supported with PCManFM wallpaper.\n"
}



function dry_run() {
    printf "* PCManFM: set desktop wallpaper.\n"
}



function print_module_help() {
    echo "Help for GCS ${BASH_SOURCE##*/} module"
    echo
    echo "This module sets the desktop wallpaper for PCManFM (when it is used to display desktop icons). This is accomplished by using command-line switches provided by PCManFM itself."
    echo "A few settings (background color, text color, shadow color) cannot be changed via the command line. This is only possible using the patched version at https://github.com/livanh/pcmanfm."
    echo
    echo "Backup and restore are not supported."
    echo
}



function apply_theme() {
    if ! [ -f "${wallpaper_file}" ]; then
        printf "* Not setting wallpaper with PCManFM (image file not found: \"${wallpaper_image}\").\n"

    elif ! pgrep -f "^pcmanfm --desktop" >/dev/null; then
        printf "* Not setting wallpaper with PCManFM (desktop manager is not active).\n"

    else
        printf "* Setting wallpaper with PCManFM..."

        case "${wallpaper_mode}" in
            centered)  pcmanfm --wallpaper-mode=center  --set-wallpaper "${wallpaper_file}";;
            tiled)     pcmanfm --wallpaper-mode=tile    --set-wallpaper "${wallpaper_file}";;
            stretched) pcmanfm --wallpaper-mode=stretch --set-wallpaper "${wallpaper_file}";;
            zoom-fit)  pcmanfm --wallpaper-mode=fit     --set-wallpaper "${wallpaper_file}";;
            zoom-fill) pcmanfm --wallpaper-mode=crop    --set-wallpaper "${wallpaper_file}";;
        esac

        # these require a patched version of PCManFM: https://github.com/livanh/pcmanfm (master-with-improvements branch)
        pcmanfm --wallpaper-bg-color ${wallpaper_bg_color}
        pcmanfm --desktop-text-color ${wallpaper_text_color}
        pcmanfm --desktop-shadow-color ${wallpaper_shadow_color}

        local DESKTOP_BACKGROUND_SYMLINK="${HOME}/.config/desktop-background"
        [ -e "${DESKTOP_BACKGROUND_SYMLINK}" ] && rm "${DESKTOP_BACKGROUND_SYMLINK}"
        ln -s "${wallpaper_file}" "${DESKTOP_BACKGROUND_SYMLINK}"

        printf " done.\n"

    fi
}

