#!/bin/bash

# TODO: handle cases when $wallpaper_image, $wallpaper_mode or $wallpaper_bg_color is not set by the theme

which nitrogen >/dev/null || return

NITROGEN_ENABLE_DEFAULT="true"
NITROGEN_ENABLE="$(crudini --get ${CONFIG_FILE} nitrogen enable 2>/dev/null || echo "${NITROGEN_ENABLE_DEFAULT}")"

if ! [ "${NITROGEN_ENABLE}" == "true" ]; then
    printf "* Not setting wallpaper with nitrogen (disabled from configuration).\n"
    
elif ! [ -f "${COLOR_THEME_DIR}/${wallpaper_image}" ]; then
    printf "* Not setting wallpaper with nitrogen (image file not found: \"${COLOR_THEME_DIR}/${wallpaper_image}\").\n"
    
else
    printf "* Setting wallpaper with nitrogen..."
    case "${wallpaper_mode}" in
        centered)  nitrogen --save --set-centered "${COLOR_THEME_DIR}/${wallpaper_image}" --set-color=${wallpaper_bg_color};;
        tiled)     nitrogen --save --set-tiled "${COLOR_THEME_DIR}/${wallpaper_image}";;
        stretched) nitrogen --save --set-scaled "${COLOR_THEME_DIR}/${wallpaper_image}";;
        zoom-fit)  nitrogen --save --set-zoom "${COLOR_THEME_DIR}/${wallpaper_image}" --set-color=${wallpaper_bg_color};;
        zoom-fill) nitrogen --save --set-zoom-fill "${COLOR_THEME_DIR}/${wallpaper_image}";;
    esac
    printf " done.\n"
fi
