#!/bin/bash

# TODO: handle cases when $wallpaper_image, $wallpaper_mode or $wallpaper_bg_color is not set by the theme
# TODO: can not set background/text color from command line, prepare a patch for pcmanfm 

which pcmanfm >/dev/null || return

BACKGROUND_PCMANFM_ENABLE_DEFAULT="true"
BACKGROUND_PCMANFM_ENABLE="$(crudini --get ${CONFIG_FILE} background-pcmanfm enable 2>/dev/null || echo "${BACKGROUND_PCMANFM_ENABLE_DEFAULT}")"

if ! [ "${BACKGROUND_PCMANFM_ENABLE}" == "true" ]; then
    printf "* Not setting wallpaper with pcmanfm (disabled from configuration).\n"
    
elif ! [ -f "${COLOR_THEME_DIR}/${wallpaper_image}" ]; then
    printf "* Not setting wallpaper with pcmanfm (image file not found: \"${COLOR_THEME_DIR}/${wallpaper_image}\").\n"
    
elif ! pgrep -f "pcmanfm --desktop" >/dev/null; then
    printf "* Not setting wallpaper with pcmanfm (desktop manager is not active).\n"
    
else
    printf "* Setting wallpaper with pcmanfm..."
    case "${wallpaper_mode}" in
        centered)  pcmanfm --wallpaper-mode=center  --set-wallpaper "${COLOR_THEME_DIR}/${wallpaper_image}";;
        tiled)     pcmanfm --wallpaper-mode=tile    --set-wallpaper "${COLOR_THEME_DIR}/${wallpaper_image}";;
        stretched) pcmanfm --wallpaper-mode=stretch --set-wallpaper "${COLOR_THEME_DIR}/${wallpaper_image}";;
        zoom-fit)  pcmanfm --wallpaper-mode=fit     --set-wallpaper "${COLOR_THEME_DIR}/${wallpaper_image}";;
        zoom-fill) pcmanfm --wallpaper-mode=crop    --set-wallpaper "${COLOR_THEME_DIR}/${wallpaper_image}";;
    esac
    printf " done.\n"
fi
