#!/bin/sh

# TODO: add link colors

CHERRYTREE_CONFIG_FILE="$HOME/.config/cherrytree/config.cfg"
if [ -f "${CHERRYTREE_CONFIG_FILE}" ]; then
    printf "* Setting colors for cherrytree..."
    set_value "rt_def_fg" " = " "${text_color}" "${CHERRYTREE_CONFIG_FILE}"
    set_value "rt_def_bg" " = " "${base_color}" "${CHERRYTREE_CONFIG_FILE}"
    set_value "tt_def_fg" " = " "${text_color}" "${CHERRYTREE_CONFIG_FILE}"
    set_value "tt_def_bg" " = " "${base_color}" "${CHERRYTREE_CONFIG_FILE}"
    printf " done.\n"
fi
