#!/bin/bash

which cherrytree >/dev/null || return

: ${cherrytree_window_fg:=${text_color}}
: ${cherrytree_window_bg:=${base_color}}
: ${cherrytree_tree_fg:=${text_color}}
: ${cherrytree_tree_bg:=${base_color}}
: ${cherrytree_link_web:=${link_color}}
: ${cherrytree_link_node:=${link_color}}
: ${cherrytree_link_file:=${link_color}}
: ${cherrytree_link_directory:=${link_color}}

CHERRYTREE_ENABLE_DEFAULT="true"
CHERRYTREE_CONFIG_FILE_DEFAULT="$HOME/.config/cherrytree/config.cfg"

CHERRYTREE_ENABLE="$(crudini      --get ${CONFIG_FILE} cherrytree enable      2>/dev/null || echo "${CHERRYTREE_ENABLE_DEFAULT}")"
CHERRYTREE_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} cherrytree config_file 2>/dev/null || echo "${CHERRYTREE_CONFIG_FILE_DEFAULT}")"

if ! [ "${CHERRYTREE_ENABLE}" == "true" ]; then
    printf "* Not setting colors for cherrytree (disabled from configuration).\n"

elif ! [ -f "${CHERRYTREE_CONFIG_FILE}" ]; then
    printf "* Not setting colors for cherrytree (configuration file ${CHERRYTREE_CONFIG_FILE} not found).\n"

else
    printf "* Setting colors for cherrytree..."
    set_value "rt_def_fg"     " = " "${cherrytree_window_fg}"      "${CHERRYTREE_CONFIG_FILE}"
    set_value "rt_def_bg"     " = " "${cherrytree_window_bg}"      "${CHERRYTREE_CONFIG_FILE}"
    set_value "tt_def_fg"     " = " "${cherrytree_tree_fg}"        "${CHERRYTREE_CONFIG_FILE}"
    set_value "tt_def_bg"     " = " "${cherrytree_tree_bg}"        "${CHERRYTREE_CONFIG_FILE}"
    set_value "col_link_webs" " = " "${cherrytree_link_web}"       "${CHERRYTREE_CONFIG_FILE}"
    set_value "col_link_node" " = " "${cherrytree_link_node}"      "${CHERRYTREE_CONFIG_FILE}"
    set_value "col_link_file" " = " "${cherrytree_link_file}"      "${CHERRYTREE_CONFIG_FILE}"
    set_value "col_link_fold" " = " "${cherrytree_link_directory}" "${CHERRYTREE_CONFIG_FILE}"
    printf " done.\n"
fi
