#!/bin/bash

which conky >/dev/null || return

CONKY_I3BAR_ENABLE_DEFAULT="false"
CONKY_I3BAR_CONFIG_FILE_DEFAULT="/home/alessandro/.config/conky/conkyrc_i3bar"

CONKY_I3BAR_ENABLE="$(crudini      --get ${CONFIG_FILE} conky-i3bar enable      2>/dev/null || echo "${CONKY_I3BAR_ENABLE_DEFAULT}")"
CONKY_I3BAR_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} conky-i3bar config_file 2>/dev/null || echo "${CONKY_I3BAR_CONFIG_FILE_DEFAULT}" )"
eval conky_color0="$(crudini --get ${CONFIG_FILE} conky-i3bar color0 2>/dev/null || echo ${text_color} )"

if ! [ "${CONKY_I3BAR_ENABLE}" == "true" ]; then
    printf "* Not setting colors for conky in i3bar (disabled from configuration).\n"

elif ! [ -f "${CONKY_I3BAR_CONFIG_FILE}" ]; then
    printf "* Not setting colors for conky in i3bar (configuration file \"${CONKY_I3BAR_CONFIG_FILE}\" not found).\n"

else
    printf "* Setting colors for conky in i3bar..."
    sed -i "s/\"color\" : \".*\"/\"color\" : \"@${conky_color0:1}\"/g" "${CONKY_I3BAR_CONFIG_FILE}"
    printf " done.\n"
fi
