#!/bin/bash
CONKY_I3BAR_CONFIG_FILE="/home/alessandro/.config/conky/conkyrc_i3bar"
if [ -f "${CONKY_I3BAR_CONFIG_FILE}" ]; then
    printf "* Setting colors for conky (i3bar)..."
    sed -i "s/\"color\" : \".*\"/\"color\" : \"@${conky_color0:1}\"/g" "${CONKY_I3BAR_CONFIG_FILE}"
    printf " done.\n"
fi
