#!/bin/bash

which conky >/dev/null || return

eval conky_i3bar_color0="$(crudini --get ${CONFIG_FILE} conky-i3bar color0 2>/dev/null || echo "${conky_i3bar_color0}" )"

CONKY_I3BAR_ENABLE_DEFAULT="false"
CONKY_I3BAR_CONFIG_FILE_DEFAULT=""

CONKY_I3BAR_ENABLE="$(crudini      --get ${CONFIG_FILE} conky-i3bar enable      2>/dev/null || echo "${CONKY_I3BAR_ENABLE_DEFAULT}")"
CONKY_I3BAR_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} conky-i3bar config_file 2>/dev/null || echo "${CONKY_I3BAR_CONFIG_FILE_DEFAULT}" )"
CONKY_I3BAR_CONFIG_FILE="${CONKY_I3BAR_CONFIG_FILE//\"}"

if ! [ "${CONKY_I3BAR_ENABLE}" == "true" ]; then
    printf "* Not setting colors for conky in i3bar (disabled from configuration).\n"

elif ! [ -f "${CONKY_I3BAR_CONFIG_FILE}" ]; then
    printf "* Not setting colors for conky in i3bar (configuration file \"${CONKY_I3BAR_CONFIG_FILE}\" not found).\n"

else
    printf "* Setting colors for conky in i3bar..."
    [ -z "${conky_i3bar_color0}" ] || sed -i "s/\"color\" : \".*\"/\"color\" : \"@${conky_i3bar_color0:1}\"/g" "${CONKY_I3BAR_CONFIG_FILE}"
    printf " done.\n"
fi
