#!/bin/sh
# TODO: replace other $colorN colors
# TODO: replace background color
# TODO: do not apply colors which are not defined
# TODO: print messages only if some config file exist
source "${CONFIG_DIR}/modules/conky"
echo "* setting colors for conky..."
for i in ${CONKY_CONFIG_FILES[*]}; do
    if [ -f "${i}" ]; then
        echo "  ${i}..."
        sed -i "s/default_color .*/default_color ${text_color:1}/" "${i}"
        sed -i "s/color0 .*/color0 ${conky_color0:1}/" "${i}"
    fi
done
killall -SIGUSR1 conky
echo "  Done."
