#!/bin/bash
# TODO: replace other $colorN colors
# TODO: replace background color
# TODO: do not apply colors which are not defined
# TODO: print messages only if some config file exist

CONKY_CONFIG_FILES=$(crudini --get ${CONFIG_FILE} conky config_files 2>/dev/null || echo "${HOME}/.conkyrc")
eval conky_color0=$(crudini --get ${CONFIG_FILE} conky color0 2>/dev/null || echo ${text_color} )
CONKY_RESTART_COMMAND=$(crudini --get ${CONFIG_FILE} conky restart_command 2>/dev/null || echo )

printf "* Setting colors for conky...\n"
for i in ${CONKY_CONFIG_FILES}; do
    
    file="$i"
    if [ ${file:0:1} == \" ]; then
        file=${file:1}
    fi
    if [ ${file: -1} == \" ]; then
        file=${file:0:-1}
    fi
    
    if [ -f "${file}" ]; then
        printf "  ${file}..."
        set_value "default_color" " "  "${text_color:1}" "${file}"
        set_value "color0" " " "${conky_color0:1}" "${file}"
        printf " done.\n"
    fi
done

$CONKY_RESTART_COMMAND &>/dev/null
