#!/bin/bash

#TODO create index.theme if not existing
#TODO ~/.icons/default/cursors is always a symlink?
#TODO allow cursor themes in $HOME/.icons and/or $HOME/.local/share/icons too

if [[ $cursor_theme_name ]]; then
    printf "* Setting cursor theme: ${cursor_theme_name}..."
    set_value "Inherits" "=" "${cursor_theme_name}" "$HOME/.icons/default/index.theme"
    rm "$HOME/.icons/default/cursors"
    ln -s "/usr/share/icons/${cursor_theme_name}/cursors" "$HOME/.icons/default/cursors"
    printf " done.\n"
fi
