#!/bin/bash
#TODO is ~/.icons/default/cursors always a symlink?

function init_module() {
    CURSOR_THEME_ENABLE_DEFAULT="true"
    CURSOR_THEME_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} cursor-theme enable      2>/dev/null || echo "${CURSOR_THEME_ENABLE_DEFAULT}")"

    CURSOR_THEME_USER_PATH="${HOME}/.icons/default"
}



function check_dependencies() {
    if ! [[ ${cursor_theme_name} ]]; then
        return 1

    elif ! [ "${CURSOR_THEME_ENABLE}" == "true" ]; then
        printf "* Not setting cursor theme (disabled from configuration).\n"
        return 1

    else
        return 0

    fi
}



function derive_colors() {
    CURSOR_THEME_FOUND="false"
    for cursor_themes_directory in "/usr/share/icons" "/usr/local/share/icons" "${HOME}/.icons" "${HOME}/.local/share/icons" ; do
        if [ -d "${cursor_themes_directory}/${cursor_theme_name}" ]; then
            CURSOR_THEME_FOUND="true"
            CURSOR_THEME_PATH="${cursor_themes_directory}"
        fi
    done
}



function create_backup() {
    printf "* Backup/restore not supported for cursor theme.\n"
}



function restore_backup() {
    printf "* Backup/restore not supported for cursor theme.\n"
}



function dry_run() {
    printf "* cursor-theme: set cursor theme in \"${CURSOR_THEME_USER_PATH}/index.theme\".\n"
}



function apply_theme() {
    printf "* Setting cursor theme: ${cursor_theme_name}..."
    if [ "${CURSOR_THEME_FOUND}" == "true" ]; then
        local CURSOR_THEME_INDEX_FILE="${CURSOR_THEME_USER_PATH}/index.theme"
        if ! [ -f "${CURSOR_THEME_INDEX_FILE}" ]; then
            mkdir -p "${CURSOR_THEME_USER_PATH}"
            echo "[Icon Theme]" >  "${CURSOR_THEME_INDEX_FILE}"
            echo "Name=Default" >> "${CURSOR_THEME_INDEX_FILE}"
            echo "Comment=Default Cursor Theme" >> "${CURSOR_THEME_INDEX_FILE}"
            echo "Inherits=" >> "${CURSOR_THEME_INDEX_FILE}"
        fi

        set_value "Inherits" "=" "${cursor_theme_name}" "${CURSOR_THEME_INDEX_FILE}"
        [ -L "${CURSOR_THEME_USER_PATH}/cursors" ] && rm "${CURSOR_THEME_USER_PATH}/cursors"
        ln -s "${CURSOR_THEME_PATH}/${cursor_theme_name}/cursors" "${CURSOR_THEME_USER_PATH}/cursors"
        printf " done.\n"
    else
        printf " not found!\n"
    fi
}

