#!/bin/bash
#TODO is ~/.icons/default/cursors always a symlink?
#TODO allow cursor themes in $HOME/.icons and/or $HOME/.local/share/icons too

function init_module() {
    CURSOR_THEME_ENABLE_DEFAULT="true"
    CURSOR_THEME_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} cursor-theme enable      2>/dev/null || echo "${CURSOR_THEME_ENABLE_DEFAULT}")"

    CURSOR_THEME_USER_PATH="$HOME/.icons/default"
}



function check_dependencies() {
    if ! [[ $cursor_theme_name ]]; then
        return 1

    elif ! [ "${CURSOR_THEME_ENABLE}" == "true" ]; then
        printf "* Not setting cursor theme (disabled from configuration).\n"
        return 1

    else
        return 0

    fi
}



function derive_colors() {
    cursor_theme_found="false"
    for i in "/usr/share/icons" "usr/local/share/icons" "$HOME/.icons"; do
        if [ -d "$i/$cursor_theme_name" ]; then
            cursor_theme_found="true"
        fi
    done
}



function create_backup() {
    printf "* Backup/restore not supported for cursor theme.\n"
}



function restore_backup() {
    printf "* Backup/restore not supported for cursor theme.\n"
}



function dry_run() {
    printf "* cursor-theme: set cursor theme in \"${CURSOR_THEME_USER_PATH}/index.theme\".\n"
}



function apply_theme() {
    printf "* Setting cursor theme: ${cursor_theme_name}..."
    if [ "${cursor_theme_found}" == "true" ]; then
        cursor_theme_index="${CURSOR_THEME_USER_PATH}/index.theme"
        if ! [ -f "${cursor_theme_index}" ]; then
            mkdir -p "${CURSOR_THEME_USER_PATH}"
            echo "[Icon Theme]" >  "${cursor_theme_index}"
            echo "Name=Default" >> "${cursor_theme_index}"
            echo "Comment=Default Cursor Theme" >> "${cursor_theme_index}"
            echo "Inherits=" >> "${cursor_theme_index}"
        fi

        set_value "Inherits" "=" "${cursor_theme_name}" "${cursor_theme_index}"
        [ -L "${CURSOR_THEME_USER_PATH}/cursors" ] && rm "${CURSOR_THEME_USER_PATH}/cursors"
        ln -s "/usr/share/icons/${cursor_theme_name}/cursors" "${CURSOR_THEME_USER_PATH}/cursors"
        printf " done.\n"
    else
        printf " not found!\n"
    fi
}

