#!/bin/bash

# dmenu does not have a configuration file, so I can't write
# a universal module. This one Works For Me(TM).
#
# I run dmenu through i3-dmenu-desktop with the following section
# of the i3 config:
#
#   set $dmenu_normal_bg #542303
#   set $dmenu_normal_fg #FFF285
#   set $dmenu_selected_bg #4e9c2c
#   set $dmenu_selected_fg #ffffff
#   bindsym Mod4+F1 exec --no-startup-id i3-dmenu-desktop --dmenu="dmenu.xft -i -nb \
#     $dmenu_normal_bg -nf $dmenu_normal_fg -sb $dmenu_selected_bg -sf $dmenu_selected_fg -fn DejaVu-11 -b"
#
# therefore I'm settings colors there

which dmenu >/dev/null || return
which i3 >/dev/null || return

: ${dmenu_normal_bg:=${tray_bg}}
: ${dmenu_normal_fg:=${tray_fg}}
: ${dmenu_selected_bg:=${tray_focused_bg}}
: ${dmenu_selected_fg:=${tray_focused_fg}}

DMENU_ENABLE_DEFAULT="false"
I3_CONFIG_FILE_DEFAULT="$HOME/.config/i3/config"
DMENU_RESTART_COMMAND_DEFAULT=""

DMENU_ENABLE="$(crudini --get ${CONFIG_FILE} dmenu enable 2>/dev/null || echo "${DMENU_ENABLE_DEFAULT}")"
I3_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} i3wm config_file 2>/dev/null || echo "${I3_CONFIG_FILE_DEFAULT}")"
DMENU_RESTART_COMMAND="$(crudini --get ${CONFIG_FILE} dmenu restart_command 2>/dev/null || echo "${DMENU_RESTART_COMMAND_DEFAULT}")"

if ! [ "${DMENU_ENABLE}" == "true" ]; then
    printf "* Not setting colors for dmenu (disabled from configuration).\n"

elif ! [ -f "${I3_CONFIG_FILE}" ]; then
    printf "* Not setting colors for dmenu (configuration file \"${I3_CONFIG_FILE}\" not found).\n"

else
    printf "* Setting colors for dmenu..."
    set_value 'set \$dmenu_normal_bg'   " " "${dmenu_normal_bg}"   "${I3_CONFIG_FILE}"
    set_value 'set \$dmenu_normal_fg'   " " "${dmenu_normal_fg}"   "${I3_CONFIG_FILE}"
    set_value 'set \$dmenu_selected_bg' " " "${dmenu_selected_bg}" "${I3_CONFIG_FILE}"
    set_value 'set \$dmenu_selected_fg' " " "${dmenu_selected_fg}" "${I3_CONFIG_FILE}"
    $DMENU_RESTART_COMMAND &>/dev/null
    printf " done.\n"
fi
