#!/bin/bash
FIREFOX_CONFIG_FILES=("/home/alessandro/.mozilla/firefox/Profilo_completo/prefs.js" "/home/alessandro/.mozilla/firefox/Profilo_vuoto/prefs.js")

ff_set_value(){
    key="$1"
    value="$2"
    file="$3"
    sed -i "s/\"$1\", \".*\"/\"$1\", \"$2\"/g" "$3"
}

printf "* Setting colors for Firefox...\n"
for firefox_config_file in ${FIREFOX_CONFIG_FILES[*]}; do
    if [ -f "${firefox_config_file}" ]; then
        printf "  ${firefox_config_file}..."
        ff_set_value "extensions.classicthemerestorer.ctab1"      "${bg_color}"             "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctab2"      "${base_color}"           "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabact1"   "${bg_color}"             "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabact2"   "${bg_color}"             "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabactt"   "${text_color}"           "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabacttsh" "${selected_bg_color}"    "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabhov1"   "${bg_color}"             "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabhov2"   "${base_color}"           "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabhovt"   "${text_color}"           "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabhovtsh" "${selected_bg_color}"    "${firefox_config_file}"
        ff_set_value "extensions.classicthemerestorer.ctabt"      "${unfocused_text_color}" "${firefox_config_file}"

        ff_set_value "status4evar.status.urlbar.color" "${selected_fg_color}" "${firefox_config_file}"

        ff_set_value "extensions.sitelauncher.launcher.color.background" "${base_color}" "${firefox_config_file}"
        ff_set_value "extensions.sitelauncher.launcher.color.foreground" "${text_color}" "${firefox_config_file}"
        ff_set_value "extensions.sitelauncher.launcher.lines"            "${base_color}" "${firefox_config_file}"
        
        printf " done.\n"
    fi
done

