#!/bin/bash

which galculator >/dev/null || return

: ${galculator_bg_color:=${base_color}}
: ${galculator_result_color:=${text_color}}
: ${galculator_stack_color:=${text_color}}
: ${galculator_module_active_color:=${selected_bg_color}}
: ${galculator_module_inactive_color:=${unfocused_text_color}}

GALCULATOR_ENABLE_DEFAULT="true"
GALCULATOR_CONFIG_FILE_DEFAULT="$HOME/.config/galculator/galculator.conf"

GALCULATOR_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} galculator enable      2>/dev/null || echo "${GALCULATOR_ENABLE_DEFAULT}")"
GALCULATOR_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} galculator config_file 2>/dev/null || echo "${GALCULATOR_CONFIG_FILE_DEFAULT}")"

if ! [ "${GALCULATOR_ENABLE}" == "true" ]; then
    printf "* Ignoring Galculator (disabled from configuration).\n"

elif ! [ -f "${GALCULATOR_CONFIG_FILE}" ]; then
    printf "* Ignoring Galculator (config file \"${GALCULATOR_CONFIG_FILE}\" not found).\n"

elif [ "${GCS_ACTION}" == "create-backup" ]; then
    printf "* Making backup of Galculator configuration file..."

    GALCULATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/galculator"
    mkdir -p "${GALCULATOR_BACKUP_DIR}"
    cp "${GALCULATOR_CONFIG_FILE}" "${GALCULATOR_BACKUP_DIR}/galculator.conf"

    printf " done.\n"

elif [ "${GCS_ACTION}" == "restore-backup" ]; then
    printf "* Restoring backup of Galculator configuration file..."

    GALCULATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/galculator"
    if [ -f "${GALCULATOR_BACKUP_DIR}/galculator.conf" ]; then
        cp "${GALCULATOR_BACKUP_DIR}/galculator.conf" "${GALCULATOR_CONFIG_FILE}"
        printf " done.\n"
    else
        printf " not found!\n"
    fi

elif [ "${GCS_ACTION}" == "apply-theme" ]; then
    printf "* Setting colors for Galculator..."

    GALCULATOR_TMP_DIR="${GCS_TMP_DIR}/galculator"
    GALCULATOR_TMP_CONFIG_FILE="${GALCULATOR_TMP_DIR}/galculator.conf"
    mkdir "${GALCULATOR_TMP_DIR}"
    cp "${GALCULATOR_CONFIG_FILE}" "${GALCULATOR_TMP_CONFIG_FILE}"

    set_value "display_bkg_color"             "=" "\"${galculator_bg_color}\""              "${GALCULATOR_TMP_CONFIG_FILE}"
    set_value "display_result_color"          "=" "\"${galculator_result_color}\""          "${GALCULATOR_TMP_CONFIG_FILE}"
    set_value "display_stack_color"           "=" "\"${galculator_stack_color}\""           "${GALCULATOR_TMP_CONFIG_FILE}"
    set_value "display_module_active_color"   "=" "\"${galculator_module_active_color}\""   "${GALCULATOR_TMP_CONFIG_FILE}"
    set_value "display_module_inactive_color" "=" "\"${galculator_module_inactive_color}\"" "${GALCULATOR_TMP_CONFIG_FILE}"

    mv "${GALCULATOR_TMP_CONFIG_FILE}" "${GALCULATOR_CONFIG_FILE}"

    printf " done.\n"

fi

