#!/bin/sh

GEANY_CONFIG_FILE="$HOME/.config/geany/geany.conf"
if [ -f "${GEANY_CONFIG_FILE}" ]; then
    echo "* setting colors for Geany..."
    
    if [ -f "${MODULES_DIR}/geany-template.conf" ]; then
	destfile="$HOME/.config/geany/colorschemes/gcs.conf"
	cp "${MODULES_DIR}/geany-template.conf" "${destfile}"
	
	set_value "editor_bg"           "=" "${editor_bg}"           "${destfile}"
	set_value "editor_fg"           "=" "${editor_fg}"           "${destfile}"
	set_value "editor_selected_bg"  "=" "${editor_selected_bg}"  "${destfile}"
	set_value "editor_selected_fg"  "=" "${editor_selected_fg}"  "${destfile}"
	set_value "editor_frame_bg"     "=" "${editor_frame_bg}"     "${destfile}"
	set_value "editor_frame_fg"     "=" "${editor_frame_fg}"     "${destfile}"
	
	set_value "editor_number"       "=" "${editor_number}"       "${destfile}"
	set_value "editor_class"        "=" "${editor_class}"        "${destfile}"
	set_value "editor_string"       "=" "${editor_string}"       "${destfile}"
	set_value "editor_operator"     "=" "${editor_operator}"     "${destfile}"
	set_value "editor_comment"      "=" "${editor_comment}"      "${destfile}"
	set_value "editor_error"        "=" "${editor_error}"        "${destfile}"
	set_value "editor_keyword"      "=" "${editor_keyword}"      "${destfile}"
	set_value "editor_character"    "=" "${editor_character}"    "${destfile}"
	set_value "editor_preprocessor" "=" "${editor_preprocessor}" "${destfile}"
	
	set_value "color_scheme" "=" "gcs.conf"             "${GEANY_CONFIG_FILE}"
	set_value "colour_fore"  "=" "${terminal_fg_color}" "${GEANY_CONFIG_FILE}"
	set_value "colour_back"  "=" "${terminal_bg_color}" "${GEANY_CONFIG_FILE}"
	
	echo "  Done." 
    else
	echo "  Error: template not found!"
    fi
    
fi
