#!/bin/sh

# TODO: define common colors (in theme files) for syntax highlighting of keywords, operators, etc.
# TODO: template needs to be cleaned a bit
# TODO: set colors for Geany terminal emulator

GEANY_CONFIG_FILE="$HOME/.config/geany/geany.conf"
if [ -f "${GEANY_CONFIG_FILE}" ]; then
    echo "* setting colors for Geany..."
    
    if [ -f "${MODULES_DIR}/geany-template.conf" ]; then
	destfile="$HOME/.config/geany/colorschemes/gcs.conf"
	cp "${MODULES_DIR}/geany-template.conf" "${destfile}"
	
	set_value "base_color"        "=" "$base_color"        "${destfile}"
	set_value "fg_color"          "=" "$fg_color"          "${destfile}"
	set_value "selected_bg_color" "=" "$selected_bg_color" "${destfile}"
	set_value "selected_fg_color" "=" "$selected_fg_color" "${destfile}"
	set_value "text_color"        "=" "$text_color"        "${destfile}"
	set_value "bg_color"          "=" "$bg_color"          "${destfile}"
	set_value "tooltip_fg_color"  "=" "$tooltip_fg_color"  "${destfile}"
	set_value "tooltip_bg_color"  "=" "$tooltip_bg_color"  "${destfile}"
	
	set_value "color_scheme" "=" "gcs.conf"             "${GEANY_CONFIG_FILE}"
	set_value "colour_fore"  "=" "${terminal_fg_color}" "${GEANY_CONFIG_FILE}"
	set_value "colour_back"  "=" "${terminal_bg_color}" "${GEANY_CONFIG_FILE}"
	
	echo "  Done." 
    else
	echo "  Error: template not found!"
    fi
    
fi
