#!/bin/bash

which gnome-terminal >/dev/null || return
which dconf >/dev/null || return

: ${gnome_terminal_bg_color:=${terminal_bg_color}}
: ${gnome_terminal_fg_color:=${terminal_fg_color}}

GNOME_TERMINAL_ENABLE_DEFAULT="true"
GNOME_TERMINAL_PROFILE_DEFAULT="Default"

GNOME_TERMINAL_ENABLE="$(crudini  --get ${GCS_CONFIG_FILE} gnome-terminal enable  2>/dev/null || echo "${GNOME_TERMINAL_ENABLE_DEFAULT}")"
GNOME_TERMINAL_PROFILE="$(crudini --get ${GCS_CONFIG_FILE} gnome-terminal profile 2>/dev/null || echo "${GNOME_TERMINAL_PROFILE_DEFAULT}")"

GNOME_TERMINAL_DCONF_PATH="/org/gnome/terminal/legacy/profiles:"

if ! [ "${GNOME_TERMINAL_ENABLE}" == "true" ]; then
    printf "* Ignoring GNOME Terminal (disabled from configuration).\n"

elif ! which dconf >/dev/null; then
    printf "* Ignoring GNOME Terminal (dconf not found).\n"

elif [ "${GCS_ACTION}" == "create-backup" ]; then
    printf "* Making backup of colors for GNOME Terminal..."

    GNOME_TERMINAL_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/gnome-terminal"
    mkdir -p "${GNOME_TERMINAL_BACKUP_DIR}"

    shopt -s lastpipe
    dconf dump "${GNOME_TERMINAL_DCONF_PATH}/" \
    | awk '/\[:/||/visible-name=/' \
    | while read i; do
        if [ "${i:0:1}" == "[" ]; then
            gnome_terminal_profile_id="${i:1:-1}"
        elif [ "${i}" == "${GNOME_TERMINAL_PROFILE}" ]; then
            break
        fi
    done
    shopt -u lastpipe
    dconf read "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/use-theme-colors" > "${GNOME_TERMINAL_BACKUP_DIR}/use-theme-colors"
    dconf read "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/background-color" > "${GNOME_TERMINAL_BACKUP_DIR}/background-color"
    dconf read "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/foreground-color" > "${GNOME_TERMINAL_BACKUP_DIR}/foreground-color"
    printf " done.\n"

elif [ "${GCS_ACTION}" == "restore-backup" ]; then
    printf "* Restoring backup of colors for GNOME Terminal..."

    GNOME_TERMINAL_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/gnome-terminal"

    shopt -s lastpipe
    dconf dump "${GNOME_TERMINAL_DCONF_PATH}/" \
    | awk '/\[:/||/visible-name=/' \
    | while read i; do
        if [ "${i:0:1}" == "[" ]; then
            gnome_terminal_profile_id="${i:1:-1}"
        elif [ "${i}" == "${GNOME_TERMINAL_PROFILE}" ]; then
            break
        fi
    done
    shopt -u lastpipe

    if [ -f "${GNOME_TERMINAL_BACKUP_DIR}/use-theme-colors" ]; then
        dconf write "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/use-theme-colors" $(cat "${GNOME_TERMINAL_BACKUP_DIR}/use-theme-colors")
    fi

    if [ -f "${GNOME_TERMINAL_BACKUP_DIR}/background-color" ]; then
        dconf write "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/background-color" $(cat "${GNOME_TERMINAL_BACKUP_DIR}/background-color")
    fi

    if [ -f "${GNOME_TERMINAL_BACKUP_DIR}/foreground-color" ]; then
        dconf write "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/foreground-color" $(cat "${GNOME_TERMINAL_BACKUP_DIR}/foreground-color")
    fi

    printf " done.\n"

elif [ "${GCS_ACTION}" == "apply-theme" ]; then
    printf "* Setting colors for GNOME Terminal..."
    shopt -s lastpipe
    dconf dump "${GNOME_TERMINAL_DCONF_PATH}/" \
    | awk '/\[:/||/visible-name=/' \
    | while read i; do
        if [ "${i:0:1}" == "[" ]; then
            gnome_terminal_profile_id="${i:1:-1}"
        elif [ "${i}" == "${GNOME_TERMINAL_PROFILE}" ]; then
            break
        fi
    done
    shopt -u lastpipe
    dconf write "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/use-theme-colors" "false"
    dconf write "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/background-color" "'${gnome_terminal_bg_color}'"
    dconf write "${GNOME_TERMINAL_DCONF_PATH}/${gnome_terminal_profile_id}/foreground-color" "'${gnome_terminal_fg_color}'"
    printf " done.\n"

fi

