#!/bin/bash

# TODO: set parameters in configuration file?
printf "* Setting colors and icon theme for GTK+..."

TMPFILE="/tmp/.oomox-theme"

echo "NAME=gcs-theme" > "${TMPFILE}"
echo "BG=${gtk_bg_color:1}" >> "${TMPFILE}"
echo "FG=${gtk_fg_color:1}" >> "${TMPFILE}"
echo "MENU_BG=${gtk_menu_bg_color:1}" >> "${TMPFILE}"
echo "MENU_FG=${gtk_menu_fg_color:1}" >> "${TMPFILE}"
echo "SEL_BG=${gtk_selected_bg_color:1}" >> "${TMPFILE}"
echo "SEL_FG=${gtk_selected_fg_color:1}" >> "${TMPFILE}"
echo "TXT_BG=${gtk_base_color:1}" >> "${TMPFILE}"
echo "TXT_FG=${gtk_text_color:1}" >> "${TMPFILE}"
echo "BTN_BG=${gtk_button_bg_color:1}" >> "${TMPFILE}"
echo "BTN_FG=${gtk_button_fg_color:1}" >> "${TMPFILE}"
echo "HDR_BTN_BG=${gtk_header_button_bg_color:1}" >> "${TMPFILE}"
echo "HDR_BTN_FG=${gtk_header_button_bg_color:1}" >> "${TMPFILE}"
echo "GTK3_GENERATE_DARK=False" >> "${TMPFILE}"
echo "ROUNDNESS=3" >> "${TMPFILE}"
echo "SPACING=3" >> "${TMPFILE}"
echo "GRADIENT=0.14" >> "${TMPFILE}"

oomox-cli -o gcs-theme "${TMPFILE}" >/dev/null 2>/dev/null
rm "${TMPFILE}"

if ps -e | grep xsettings >/dev/null; then


    set_value "Net\/ThemeName" " " "\"gcs-theme\"" "$HOME/.xsettingsd"
    
    set_value "Net\/IconThemeName" " " "\"${icon_theme_name}\"" "$HOME/.xsettingsd"
    
    killall -SIGHUP xsettingsd
    
    printf " done.\n"
    
elif ps -e | grep gnome-session >/dev/null; then
    
    gtk_theme_name=$(gsettings get org.gnome.desktop.interface gtk-theme)
    
    gsettings set org.gnome.desktop.interface gtk-theme "$gcs-theme"
    
    gsettings set org.gnome.desktop.interface icon-theme "${icon_theme_name}"
    
    printf " done.\n"
    
else
    printf " no supported XSettings manager found!\n"
    # TODO: configure theme/colors with .gtkrc-2.0 and .config/gtk-3.0/settings.ini
fi
