#!/bin/bash

function init_module() {
    LXTERMINAL_ENABLE_DEFAULT="true"
    LXTERMINAL_CONFIG_FILE_DEFAULT="${HOME}/.config/lxterminal/lxterminal.conf"

    LXTERMINAL_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} lxterminal enable      2>/dev/null || echo "${LXTERMINAL_ENABLE_DEFAULT}")"
    LXTERMINAL_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} lxterminal config_file 2>/dev/null || echo "${LXTERMINAL_CONFIG_FILE_DEFAULT}")"
}



function check_dependencies() {
    if ! which lxterminal >/dev/null; then
        return 1

    elif ! [ "${LXTERMINAL_ENABLE}" == "true" ]; then
        printf "* Ignoring LXTerminal (disabled from configuration).\n"
        return 1

    elif ! [ -f "${LXTERMINAL_CONFIG_FILE}" ]; then
        printf "* Ignoring LXTerminal (configuration file \"${LXTERMINAL_CONFIG_FILE}\" not found).\n"
        return 1

    else
        return 0

    fi
}



function derive_colors() {
    : ${lxterminal_bg_color:=${terminal_bg_color}}
    : ${lxterminal_fg_color:=${terminal_fg_color}}
}



function create_backup() {
    gcs_backup_file "LXTerminal" "lxterminal" "${LXTERMINAL_CONFIG_FILE}"
}



function restore_backup() {
    gcs_restore_file "LXTerminal" "lxterminal" "${LXTERMINAL_CONFIG_FILE}"
}



function dry_run() {
    printf "* LXTerminal: set text, background, and palette colors in \"${LXTERMINAL_CONFIG_FILE}\".\n"
}



function print_module_help() {
    echo "Help for GCS ${BASH_SOURCE##*/} module"
    echo
    echo "This module sets background, foreground, and palette colors for LXTerminal. This is accomplished by modifiying the configuration file, so it is recommended that LXTerminal is not running when this module is used."
    echo
    echo "Backup and restore are supported."
    echo
}



function apply_theme() {
    printf "* Setting colors for LXTerminal..."

    local LXTERMINAL_TMP_DIR="${GCS_TMP_DIR}/lxterminal"
    local LXTERMINAL_TMP_CONFIG_FILE="${LXTERMINAL_TMP_DIR}/lxterminal.conf"
    mkdir "${LXTERMINAL_TMP_DIR}"
    cp "${LXTERMINAL_CONFIG_FILE}" "${LXTERMINAL_TMP_CONFIG_FILE}"

    set_value "bgcolor"          "=" "${lxterminal_bg_color}"           "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "fgcolor"          "=" "${lxterminal_fg_color}"           "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_0"  "=" "${terminal_palette_black}"        "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_1"  "=" "${terminal_palette_red}"          "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_2"  "=" "${terminal_palette_green}"        "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_3"  "=" "${terminal_palette_yellow}"       "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_4"  "=" "${terminal_palette_blue}"         "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_5"  "=" "${terminal_palette_purple}"       "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_6"  "=" "${terminal_palette_cyan}"         "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_7"  "=" "${terminal_palette_white}"        "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_8"  "=" "${terminal_palette_light_black}"  "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_9"  "=" "${terminal_palette_light_red}"    "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_10" "=" "${terminal_palette_light_green}"  "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_11" "=" "${terminal_palette_light_yellow}" "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_12" "=" "${terminal_palette_light_blue}"   "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_13" "=" "${terminal_palette_light_purple}" "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_14" "=" "${terminal_palette_light_cyan}"   "${LXTERMINAL_TMP_CONFIG_FILE}"
    set_value "palette_color_15" "=" "${terminal_palette_light_white}"  "${LXTERMINAL_TMP_CONFIG_FILE}"

    mv "${LXTERMINAL_TMP_CONFIG_FILE}" "${LXTERMINAL_CONFIG_FILE}"

    printf " done.\n"
}

