#!/bin/bash

which mcomix >/dev/null || return

set_color_mcomix() {
    
    if [ "$#" -ne 3 ]; then
        echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
        exit 2
    fi
    
    local key="$1"
    local value="$2"
    local file="$3"
    
    local red="$(   expr 257 \* $(printf "%d" 0x${value:1:2}))"
    local green="$( expr 257 \* $(printf "%d" 0x${value:3:2}))"
    local blue="$(  expr 257 \* $(printf "%d" 0x${value:5:2}))"
    sed -i "
    /\"${key}\"/{
        : search
        /\]/ {
        b replace
        }
        N
        b search
        : replace
        s/\"${key}\".*\]/\"${key}\": \[${red},${green},${blue}\]/
    }
    " "${file}"
}

MCOMIX_ENABLE_DEFAULT="true"
MCOMIX_CONFIG_FILE_DEFAULT="$HOME/.config/mcomix/preferences.conf"

MCOMIX_ENABLE="$(crudini      --get ${CONFIG_FILE} mcomix enable      2>/dev/null || echo "${MCOMIX_ENABLE_DEFAULT}")"
MCOMIX_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} mcomix config_file 2>/dev/null || echo "${MCOMIX_CONFIG_FILE_DEFAULT}")"

if ! [ "${MCOMIX_ENABLE}" == "true" ]; then
    printf "* Not setting colors for MComix (disabled from configuration).\n"

elif ! [ -f "${MCOMIX_CONFIG_FILE}" ]; then
    printf "* Not setting colors for MComix (configuration file \"${MCOMIX_CONFIG_FILE}\" not found).\n"

else
    printf "* Setting colors for MComix..."
    set_color_mcomix "bg colour"       "${base_color}" "${MCOMIX_CONFIG_FILE}"
    set_color_mcomix "thumb bg colour" "${bg_color}"   "${MCOMIX_CONFIG_FILE}"
    printf " done.\n"
fi
