#!/bin/bash

which mcomix >/dev/null || return

set_color_mcomix() {
    
    if [ "$#" -ne 3 ]; then
        echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
        exit 2
    fi
    
    local key="$1"
    local value="$2"
    local file="$3"
    
    local red="$(   expr 257 \* $(printf "%d" 0x${value:1:2}))"
    local green="$( expr 257 \* $(printf "%d" 0x${value:3:2}))"
    local blue="$(  expr 257 \* $(printf "%d" 0x${value:5:2}))"
    sed -i "
    /\"${key}\"/{
        : search
        /\]/ {
        b replace
        }
        N
        b search
        : replace
        s/\"${key}\".*\]/\"${key}\": \[${red},${green},${blue}\]/
    }
    " "${file}"
}

: ${mcomix_bg_color:=${base_color}}
: ${mcomix_thumb_bg_color:=${bg_color}}

MCOMIX_ENABLE_DEFAULT="true"
MCOMIX_CONFIG_FILE_DEFAULT="$HOME/.config/mcomix/preferences.conf"

MCOMIX_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} mcomix enable      2>/dev/null || echo "${MCOMIX_ENABLE_DEFAULT}")"
MCOMIX_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} mcomix config_file 2>/dev/null || echo "${MCOMIX_CONFIG_FILE_DEFAULT}")"

if ! [ "${MCOMIX_ENABLE}" == "true" ]; then
    printf "* Ignoring MComix (disabled from configuration).\n"

elif ! [ -f "${MCOMIX_CONFIG_FILE}" ]; then
    printf "* Ignoring MComix (configuration file \"${MCOMIX_CONFIG_FILE}\" not found).\n"

elif [ "${GCS_ACTION}" == "create-backup" ]; then
    printf "* Making backup of MComix configuration file..."

    MCOMIX_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/mcomix"
    mkdir -p "${MCOMIX_BACKUP_DIR}"
    cp "${MCOMIX_CONFIG_FILE}" "${MCOMIX_BACKUP_DIR}/preferences.conf"

    printf " done.\n"

elif [ "${GCS_ACTION}" == "restore-backup" ]; then
    printf "* Restoring backup of MComix configuration file..."

    MCOMIX_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/mcomix"
    if [ -f "${MCOMIX_BACKUP_DIR}/preferences.conf" ]; then
        cp "${MCOMIX_BACKUP_DIR}/preferences.conf" "${MCOMIX_CONFIG_FILE}"
        printf " done.\n"
    else
        printf " not found!\n"
    fi

elif [ "${GCS_ACTION}" == "apply-theme" ]; then
    printf "* Setting colors for MComix..."

    MCOMIX_TMP_DIR="${GCS_TMP_DIR}/mcomix"
    MCOMIX_TMP_CONFIG_FILE="${MCOMIX_TMP_DIR}/preferences.conf"
    mkdir "${MCOMIX_TMP_DIR}"
    cp "${MCOMIX_CONFIG_FILE}" "${MCOMIX_TMP_CONFIG_FILE}"

    set_color_mcomix "bg colour"       "${mcomix_bg_color}"       "${MCOMIX_TMP_CONFIG_FILE}"
    set_color_mcomix "thumb bg colour" "${mcomix_thumb_bg_color}" "${MCOMIX_TMP_CONFIG_FILE}"

    mv "${MCOMIX_TMP_CONFIG_FILE}" "${MCOMIX_CONFIG_FILE}"

    printf " done.\n"

fi

