#!/bin/bash

MELD_GTKRC_FILE="$HOME/.gtkrc.mine"
if [ -f "${MELD_GTKRC_FILE}" ]; then

    printf "* Setting colors for Meld..."
    
    set_value "color\[\"insert-bg\"\]"               " = " "\"${meld_insert_bg}\""               "${MELD_GTKRC_FILE}"
    set_value "color\[\"insert-outline\"\]"          " = " "\"${meld_insert_outline}\""          "${MELD_GTKRC_FILE}"
    set_value "color\[\"insert-text\"\]"             " = " "\"${meld_insert_text}\""             "${MELD_GTKRC_FILE}"
    set_value "color\[\"delete-bg\"\]"               " = " "\"${meld_delete_bg}\""               "${MELD_GTKRC_FILE}"
    set_value "color\[\"delete-outline\"\]"          " = " "\"${meld_delete_outline}\""          "${MELD_GTKRC_FILE}"
    set_value "color\[\"delete-text\"\]"             " = " "\"${meld_delete_text}\""             "${MELD_GTKRC_FILE}"
    set_value "color\[\"replace-bg\"\]"              " = " "\"${meld_replace_bg}\""              "${MELD_GTKRC_FILE}"
    set_value "color\[\"replace-outline\"\]"         " = " "\"${meld_replace_outline}\""         "${MELD_GTKRC_FILE}"
    set_value "color\[\"replace-text\"\]"            " = " "\"${meld_replace_text}\""            "${MELD_GTKRC_FILE}"
    set_value "color\[\"conflict-bg\"\]"             " = " "\"${meld_conflict_bg}\""             "${MELD_GTKRC_FILE}"
    set_value "color\[\"conflict-outline\"\]"        " = " "\"${meld_conflict_outline}\""        "${MELD_GTKRC_FILE}"
    set_value "color\[\"conflict-text\"\]"           " = " "\"${meld_conflict_text}\""           "${MELD_GTKRC_FILE}"
    set_value "color\[\"error-bg\"\]"                " = " "\"${meld_error_bg}\""                "${MELD_GTKRC_FILE}"
    set_value "color\[\"error-outline\"\]"           " = " "\"${meld_error_outline}\""           "${MELD_GTKRC_FILE}"
    set_value "color\[\"error-text\"\]"              " = " "\"${meld_error_text}\""              "${MELD_GTKRC_FILE}"
    set_value "color\[\"inline-bg\"\]"               " = " "\"${meld_inline_bg}\""               "${MELD_GTKRC_FILE}"
    set_value "color\[\"inline-fg\"\]"               " = " "\"${meld_inline_fg}\""               "${MELD_GTKRC_FILE}"
    set_value "color\[\"unknown-text\"\]"            " = " "\"${meld_unknown_text}\""            "${MELD_GTKRC_FILE}"
    set_value "color\[\"current-line-highlight\"\]"  " = " "\"${meld_current_line_highlight}\""  "${MELD_GTKRC_FILE}"
    set_value "color\[\"syncpoint-outline\"\]"       " = " "\"${meld_syncpoint_outline}\""       "${MELD_GTKRC_FILE}"
    set_value "color\[\"current-chunk-highlight\"\]" " = " "\"${meld_current_chunk_highlight}\"" "${MELD_GTKRC_FILE}"
    
    printf " done.\n"
    
fi
