#!/bin/bash

NMCLI_DMENU_CONFIG_FILE="$HOME/.config/networkmanager-dmenu/config.ini"
if [ -f "${NMCLI_DMENU_CONFIG_FILE}" ]; then
    printf "* Setting colors for nmcli_dmenu..."
    set_value "nb" " = " "${bg_color}"          "${NMCLI_DMENU_CONFIG_FILE}"
    set_value "nf" " = " "${fg_color}"          "${NMCLI_DMENU_CONFIG_FILE}"
    set_value "sb" " = " "${selected_bg_color}" "${NMCLI_DMENU_CONFIG_FILE}"
    set_value "sf" " = " "${selected_fg_color}" "${NMCLI_DMENU_CONFIG_FILE}"
    printf " done.\n"
fi
