#!/bin/bash

# FIXME: set_value_section doesn't work, why?

which octave >/dev/null || return

: ${octave_terminal_bg:=${terminal_bg_color}}
: ${octave_terminal_fg:=${terminal_fg_color}}
: ${octave_terminal_selection:=${selected_bg_color}}
: ${octave_terminal_cursor:=${terminal_fg_color}}

: ${octave_current_line_bg:=${editor_current_line_bg}}

: ${octave_workpace_automatic:=${editor_class}}
: ${octave_workpace_function:=${editor_number}}
: ${octave_workpace_global:=${editor_keyword}}
: ${octave_workpace_hidden:=${editor_operator}}
: ${octave_workpace_inherited:=${editor_string}}
: ${octave_workpace_persistent:=${editor_preprocessor}}

: ${octave_text_fg:=${editor_fg}}
: ${octave_text_bg:=${editor_bg}}

: ${octave_matlab_default_fg:=${editor_fg}}
: ${octave_matlab_default_bg:=${editor_bg}}
: ${octave_matlab_comment_fg:=${editor_comment}}
: ${octave_matlab_comment_bg:=${editor_bg}}
: ${octave_matlab_command_fg:=${editor_class}}
: ${octave_matlab_command_bg:=${editor_bg}}
: ${octave_matlab_number_fg:=${editor_number}}
: ${octave_matlab_number_bg:=${editor_bg}}
: ${octave_matlab_keyword_fg:=${editor_keyword}}
: ${octave_matlab_keyword_bg:=${editor_bg}}
: ${octave_matlab_string_single_quote_fg:=${editor_string}}
: ${octave_matlab_string_single_quote_bg:=${editor_bg}}
: ${octave_matlab_operator_fg:=${editor_operator}}
: ${octave_matlab_operator_bg:=${editor_bg}}
: ${octave_matlab_identifier_fg:=${editor_fg}}
: ${octave_matlab_identifier_bg:=${editor_bg}}
: ${octave_matlab_string_double_quote_fg:=${editor_string}}
: ${octave_matlab_string_double_quote_bg:=${editor_bg}}

OCTAVE_ENABLE_DEFAULT="true"
OCTAVE_CONFIG_FILE_DEFAULT="$HOME/.config/octave/qt-settings"

OCTAVE_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} octave enable      2>/dev/null || echo "${OCTAVE_ENABLE_DEFAULT}")"
OCTAVE_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} octave config_file 2>/dev/null || echo "${OCTAVE_CONFIG_FILE_DEFAULT}")"

if ! [ "${OCTAVE_ENABLE}" == "true" ]; then
    printf "* Not setting colors for Octave (disabled from configuration).\n"

elif [ "${editor_syntax_enable}" == "false" ]; then

    if [ -f "${OCTAVE_CONFIG_FILE}" ]; then

        OCTAVE_TMP_DIR="${GCS_TMP_DIR}/octave"
        OCTAVE_TMP_CONFIG_FILE="${OCTAVE_TMP_DIR}/qt-settings"
        mkdir "${OCTAVE_TMP_DIR}"
        cp "${OCTAVE_CONFIG_FILE}" "${OCTAVE_TMP_CONFIG_FILE}"

        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_b" "${terminal_bg_color}"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_f" "${terminal_fg_color}"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_s" "${selected_bg_color}"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_c" "${terminal_fg_color}"

        # apply defaut colors
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "editor" "highlight_current_line_color" "#F0F0F0"

        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_a" "#BEFFFF"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_f" "#DCFFDC"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_g" "#DCDCFF"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_h" "#FFFFBE"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_i" "#FFDCDC"
        crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_p" "#FFBEFF"

        set_value "Octave\\\\defaultcolor"    "=" "$(printf "%d" 0x000000)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\defaultpaper"    "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style0\\\\color" "=" "$(printf "%d" 0x000000)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style0\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style1\\\\color" "=" "$(printf "%d" 0x00AA00)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style1\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style2\\\\color" "=" "$(printf "%d" 0x7F7F00)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style2\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style3\\\\color" "=" "$(printf "%d" 0xAAAA00)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style3\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style4\\\\color" "=" "$(printf "%d" 0xF0FFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style4\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style5\\\\color" "=" "$(printf "%d" 0xAAAA00)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style5\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style6\\\\color" "=" "$(printf "%d" 0xDD0000)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style6\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style7\\\\color" "=" "$(printf "%d" 0x000000)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style7\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style8\\\\color" "=" "$(printf "%d" 0xFFAA00)" "${OCTAVE_TMP_CONFIG_FILE}"
        set_value "Octave\\\\style8\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_TMP_CONFIG_FILE}"

        mv "${OCTAVE_TMP_CONFIG_FILE}" "${OCTAVE_CONFIG_FILE}"

    fi

elif ! [ -f "${OCTAVE_CONFIG_FILE}" ]; then
    printf "* Not setting colors for Octave (configuration \"${OCTAVE_CONFIG_FILE}\" not found).\n"

else
    printf "* Setting colors for Octave..."

    OCTAVE_TMP_DIR="${GCS_TMP_DIR}/octave"
    OCTAVE_TMP_CONFIG_FILE="${OCTAVE_TMP_DIR}/qt-settings"
    mkdir "${OCTAVE_TMP_DIR}"
    cp "${OCTAVE_CONFIG_FILE}" "${OCTAVE_TMP_CONFIG_FILE}"

    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_b" "${octave_terminal_bg}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_f" "${octave_terminal_fg}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_s" "${octave_terminal_selection}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "terminal" "color_c" "${octave_terminal_cursor}"

    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "editor" "highlight_current_line_color" "${octave_current_line_bg}"

    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_a" "${octave_workpace_automatic}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_f" "${octave_workpace_function}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_g" "${octave_workpace_global}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_h" "${octave_workpace_hidden}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_i" "${octave_workpace_inherited}"
    crudini --set "${OCTAVE_TMP_CONFIG_FILE}" "workspaceview" "color_p" "${octave_workpace_persistent}"

    set_value "Octave\\\\defaultcolor"    "=" "$(printf   "%d" 0x${octave_text_fg:1:6})" "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\defaultpaper"    "=" "$(printf   "%d" 0x${octave_text_bg:1:6})" "${OCTAVE_TMP_CONFIG_FILE}"

    set_value "Octave\\\\style0\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_default_fg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style0\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_default_bg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style1\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_comment_fg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style1\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_comment_bg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style2\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_command_fg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style2\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_command_bg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style3\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_number_fg:1:6})"              "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style3\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_number_bg:1:6})"              "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style4\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_keyword_fg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style4\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_keyword_bg:1:6})"             "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style5\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_string_single_quote_fg:1:6})" "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style5\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_string_single_quote_bg:1:6})" "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style6\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_operator_fg:1:6})"            "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style6\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_operator_bg:1:6})"            "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style7\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_identifier_fg:1:6})"          "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style7\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_identifier_bg:1:6})"          "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style8\\\\color" "=" "$(printf   "%d" 0x${octave_matlab_string_double_quote_fg:1:6})" "${OCTAVE_TMP_CONFIG_FILE}"
    set_value "Octave\\\\style8\\\\paper" "=" "$(printf   "%d" 0x${octave_matlab_string_double_quote_bg:1:6})" "${OCTAVE_TMP_CONFIG_FILE}"

    mv "${OCTAVE_TMP_CONFIG_FILE}" "${OCTAVE_CONFIG_FILE}"

    printf " done.\n"
fi
