#!/bin/bash

# FIXME: set_value_section doesn't work, why?

which octave >/dev/null || return

OCTAVE_CONFIG_FILE="$HOME/.config/octave/qt-settings"

if [ "${editor_syntax_enable}" == "false" ]; then
    if [ -f "${OCTAVE_CONFIG_FILE}" ]; then
        crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_b" "${terminal_bg_color}"
        crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_f" "${terminal_fg_color}"
        crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_s" "${selected_bg_color}"
        crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_c" "${terminal_fg_color}"
    fi
    
    # apply defaut colors
    crudini --set "${OCTAVE_CONFIG_FILE}" "editor" "highlight_current_line_color" "#F0F0F0"
    
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_a" "#BEFFFF"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_f" "#DCFFDC"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_g" "#DCDCFF"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_h" "#FFFFBE"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_i" "#FFDCDC"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_p" "#FFBEFF"
    
    set_value "Octave\\\\defaultcolor"    "=" "$(printf "%d" 0x000000)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\defaultpaper"    "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style0\\\\color" "=" "$(printf "%d" 0x000000)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style0\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style1\\\\color" "=" "$(printf "%d" 0x00AA00)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style1\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style2\\\\color" "=" "$(printf "%d" 0x7F7F00)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style2\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style3\\\\color" "=" "$(printf "%d" 0xAAAA00)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style3\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style4\\\\color" "=" "$(printf "%d" 0xF0FFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style4\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style5\\\\color" "=" "$(printf "%d" 0xAAAA00)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style5\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style6\\\\color" "=" "$(printf "%d" 0xDD0000)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style6\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style7\\\\color" "=" "$(printf "%d" 0x000000)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style7\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style8\\\\color" "=" "$(printf "%d" 0xFFAA00)" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style8\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"

elif [ -f "${OCTAVE_CONFIG_FILE}" ]; then

    printf "* Setting colors for Octave..."
    
    crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_b" "${terminal_bg_color}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_f" "${terminal_fg_color}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_s" "${selected_bg_color}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_c" "${terminal_fg_color}"
    
    crudini --set "${OCTAVE_CONFIG_FILE}" "editor" "highlight_current_line_color" "${editor_current_line_bg}"
    
    # TODO: obseve these in practice
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_a" "${editor_class}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_f" "${editor_number}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_g" "${editor_keyword}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_h" "${editor_operator}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_i" "${editor_string}"
    crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_p" "${editor_preprocessor}"
    
    set_value "Octave\\\\defaultcolor"    "=" "$(printf   "%d" 0x${editor_fg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\defaultpaper"    "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style0\\\\color" "=" "$(printf   "%d" 0x${editor_fg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style0\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style1\\\\color" "=" "$(printf   "%d" 0x${editor_comment:1:6})"  "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style1\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style2\\\\color" "=" "$(printf   "%d" 0x${editor_class:1:6})"    "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style2\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style3\\\\color" "=" "$(printf   "%d" 0x${editor_number:1:6})"   "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style3\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style4\\\\color" "=" "$(printf   "%d" 0x${editor_keyword:1:6})"  "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style4\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style5\\\\color" "=" "$(printf   "%d" 0x${editor_number:1:6})"   "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style5\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style6\\\\color" "=" "$(printf   "%d" 0x${editor_operator:1:6})" "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style6\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style7\\\\color" "=" "$(printf   "%d" 0x${editor_fg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style7\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style8\\\\color" "=" "$(printf   "%d" 0x${editor_string:1:6})"   "${OCTAVE_CONFIG_FILE}"
    set_value "Octave\\\\style8\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"

    printf " done.\n"

fi
