#!/bin/bash

which openbox >/dev/null || return

OPENBOX_ENABLE_DEFAULT="true"
OPENBOX_CONFIG_FILE_DEFAULT="$HOME/.config/openbox/rc.xml"
OPENBOX_RESTART_COMMAND_DEFAULT="openbox --reconfigure"

OPENBOX_ENABLE="$(crudini          --get ${CONFIG_FILE} openbox enable          2>/dev/null || echo "${OPENBOX_ENABLE_DEFAULT}")"
OPENBOX_CONFIG_FILE="$(crudini     --get ${CONFIG_FILE} openbox config_file     2>/dev/null || echo "${OPENBOX_CONFIG_FILE_DEFAULT}")"
OPENBOX_RESTART_COMMAND="$(crudini --get ${CONFIG_FILE} openbox restart_command 2>/dev/null || echo "${OPENBOX_RESTART_COMMAND_DEFAULT}")"

OPENBOX_NAMESPACE="http://openbox.org/3.4/rc"
OPENBOX_THEME_NAME_PATH="/o:openbox_config/o:theme/o:name"
OPENBOX_THEME_FILE="${HOME}/.themes/gcs-theme/openbox-3/themerc"

: ${openbox_window_active_title_bg_color:=${titlebar_focused_bg_color}}
: ${openbox_window_active_label_text_color:=${titlebar_focused_fg_color}}
: ${openbox_window_inactive_title_bg_color:=${titlebar_unfocused_bg_color}}
: ${openbox_window_inactive_label_text_color:=${titlebar_unfocused_fg_color}}

: ${openbox_window_active_button_unpressed_image_color:=${titlebar_focused_fg_color}}
: ${openbox_window_active_button_pressed_bg_color:=${titlebar_focused_fg_color}}
: ${openbox_window_active_button_pressed_image_color:=${titlebar_focused_bg_color}}
: ${openbox_window_active_button_toggled_bg_color:=${titlebar_focused_fg_color}}
: ${openbox_window_active_button_toggled_image_color:=${titlebar_focused_bg_color}}

: ${openbox_window_inactive_button_unpressed_bg_color:=${titlebar_unfocused_bg_color}}
: ${openbox_window_inactive_button_pressed_bg_color:=${titlebar_unfocused_fg_color}}
: ${openbox_window_inactive_button_pressed_image_color:=${titlebar_unfocused_bg_color}}

: ${openbox_menu_separator_color:=${text_color}}
: ${openbox_menu_items_active_text_color:=${selected_fg_color}}


if ! [ "${OPENBOX_ENABLE}" == "true" ]; then
    printf "* Not setting colors for openbox (disabled from configuration).\n"

elif ! [ -f "${OPENBOX_CONFIG_FILE}" ]; then
    printf "* Not setting colors for openbox (configuration file \"${OPENBOX_CONFIG_FILE}\" not found).\n"

elif ! pgrep openbox &>/dev/null; then
    printf "* Not setting colors for openbox (not active).\n"

else
    printf "* Setting colors for openbox..."
    xmlstarlet ed --inplace -N o="${OPENBOX_NAMESPACE}" --update "${OPENBOX_THEME_NAME_PATH}" --value "gcs-theme" "${OPENBOX_CONFIG_FILE}"
    set_value "window.active.title.bg.color:" " " "${openbox_window_active_title_bg_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.active.label.text.color:" " " "${openbox_window_active_label_text_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.inactive.title.bg.color:" " " "${openbox_window_inactive_title_bg_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.inactive.label.text.color:" " " "${openbox_window_inactive_label_text_color}" "${OPENBOX_THEME_FILE}"

    set_value "window.active.button.unpressed.image.color:" " " "${openbox_window_active_button_unpressed_image_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.active.button.pressed.image.color:" " " "${openbox_window_active_button_pressed_image_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.active.button.pressed.bg.color:" " " "${openbox_window_active_button_pressed_bg_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.active.button.toggled.bg:" " " "flat solid" "${OPENBOX_THEME_FILE}"
    set_value "window.active.button.toggled.bg.color:" " " "${openbox_window_active_button_toggled_bg_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.active.button.toggled.image.color:" " " "${openbox_window_active_button_toggled_image_color}" "${OPENBOX_THEME_FILE}"

    set_value "window.inactive.button.unpressed.bg.color:" " " "${openbox_window_inactive_button_unpressed_bg_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.inactive.button.pressed.bg.color:" " " "${openbox_window_inactive_button_pressed_bg_color}" "${OPENBOX_THEME_FILE}"
    set_value "window.inactive.button.pressed.image.color:" " " "${openbox_window_inactive_button_pressed_image_color}" "${OPENBOX_THEME_FILE}"

    set_value "menu.separator.color:" " " "${openbox_menu_separator_color}" "${OPENBOX_THEME_FILE}"
    set_value "menu.items.active.text.color:" " " "${openbox_menu_items_active_text_color}" "${OPENBOX_THEME_FILE}"

    $OPENBOX_RESTART_COMMAND &>/dev/null
    printf " done.\n"
fi
