#!/bin/bash

function init_module() {
    QT5CT_ENABLE_DEFAULT="true"
    QT5CT_CONFIG_FILE_DEFAULT="${HOME}/.config/qt5ct/qt5ct.conf"

    QT5CT_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} qt5ct enable      2>/dev/null || echo "${QT5CT_ENABLE_DEFAULT}")"
    QT5CT_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} qt5ct config_file 2>/dev/null || echo "${QT5CT_CONFIG_FILE_DEFAULT}")"
}



function check_dependencies() {
    if ! which qt5ct >/dev/null; then
        return 1

    elif ! [ "${QT5CT_ENABLE}" == "true" ]; then
        printf "* Ignoring qt5ct (disabled from configuration).\n"
        return 1

    elif ! [ -f "${QT5CT_CONFIG_FILE}" ]; then
        printf "* Ignoring qt5ct (configuration file \"${QT5CT_CONFIG_FILE}\" not found).\n"
        return 1

    else
        return 0

    fi
}



function derive_colors() {
    : ${qt5ct_icon_theme_name:=${icon_theme_name}}
}



function create_backup() {
    gcs_backup_file "qt5ct" "qt5ct" "${QT5CT_CONFIG_FILE}"
}



function restore_backup() {
    gcs_restore_file "qt5ct" "qt5ct" "${QT5CT_CONFIG_FILE}"
}



function dry_run() {
    printf "* qt5ct: set icon theme in \"${QT5CT_CONFIG_FILE}\".\n"
}



function apply_theme() {
    printf "* Setting icon theme for qt5..."


    local QT5_ICON_THEME_FOUND="false"
    if ! [ -z "${qt5ct_icon_theme_name}" ]; then
        for icon_themes_directory in "/usr/share/icons" "/usr/local/share/icons" "${HOME}/.icons" "${HOME}/.local/share/icons"; do
            if [ -d "${icon_themes_directory}/${qt5ct_icon_theme_name}" ]; then
                QT5_ICON_THEME_FOUND="true"
                break
            fi
        done
    fi


    local QT5CT_TMP_DIR="${GCS_TMP_DIR}/qt5ct"
    local QT5CT_TMP_CONFIG_FILE="${QT5CT_TMP_DIR}/qt5ct.conf"
    mkdir "${QT5CT_TMP_DIR}"
    cp "${QT5CT_CONFIG_FILE}" "${QT5CT_TMP_CONFIG_FILE}"

    crudini --set "${QT5CT_TMP_CONFIG_FILE}" "Appearance" "icon_theme" "${qt5ct_icon_theme_name}"

    mv "${QT5CT_TMP_CONFIG_FILE}" "${QT5CT_CONFIG_FILE}"

    printf " done.\n"
}

