#!/bin/bash

which qt5ct >/dev/null || return

: ${qt5ct_icon_theme_name:=${icon_theme_name}}

QT5CT_ENABLE_DEFAULT="true"
QT5CT_CONFIG_FILE_DEFAULT="$HOME/.config/qt5ct/qt5ct.conf"

QT5CT_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} qt5ct enable      2>/dev/null || echo "${QT5CT_ENABLE_DEFAULT}")"
QT5CT_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} qt5ct config_file 2>/dev/null || echo "${QT5CT_CONFIG_FILE_DEFAULT}")"

if ! [ "${QT5CT_ENABLE}" == "true" ]; then
    printf "* Ignoring qt5ct (disabled from configuration).\n"

elif ! [ -f "${QT5CT_CONFIG_FILE}" ]; then
    printf "* Ignoring qt5ct (configuration file \"${QT5CT_CONFIG_FILE}\" not found).\n"

elif [ "${GCS_ACTION}" == "create-backup" ]; then
    printf "* Making backup of qt5ct configuration file..."

    QT5CT_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/qt5ct"
    mkdir -p "${QT5CT_BACKUP_DIR}"
    cp "${QT5CT_CONFIG_FILE}" "${QT5CT_BACKUP_DIR}/qt5ct.conf"

    printf " done.\n"

elif [ "${GCS_ACTION}" == "restore-backup" ]; then
    printf "* Restoring backup of qt5ct configuration file..."

    QT5CT_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/qt5ct"
    if [ -f "${QT5CT_BACKUP_DIR}/qt5ct.conf" ]; then
        cp "${QT5CT_BACKUP_DIR}/qt5ct.conf" "${QT5CT_CONFIG_FILE}"
        printf " done.\n"
    else
        printf " not found!\n"
    fi

elif [ "${GCS_ACTION}" == "apply-theme" ]; then
    printf "* Setting icon theme for qt5..."


    icon_theme_found="false"
    if ! [ -z "${qt5ct_icon_theme_name}" ]; then
        for i in "/usr/share/icons" "usr/local/share/icons" "$HOME/.icons" "$HOME/.local/share/icons"; do
            if [ -d "$i/${qt5ct_icon_theme_name}" ]; then
                icon_theme_found="true"
            fi
        done
    fi


    QT5CT_TMP_DIR="${GCS_TMP_DIR}/qt5ct"
    QT5CT_TMP_CONFIG_FILE="${QT5CT_TMP_DIR}/qt5ct.conf"
    mkdir "${QT5CT_TMP_DIR}"
    cp "${QT5CT_CONFIG_FILE}" "${QT5CT_TMP_CONFIG_FILE}"

    crudini --set "${QT5CT_TMP_CONFIG_FILE}" "Appearance" "icon_theme" "${qt5ct_icon_theme_name}"

    mv "${QT5CT_TMP_CONFIG_FILE}" "${QT5CT_CONFIG_FILE}"

    printf " done.\n"

fi

