#!/bin/bash

function init_module() {
    TELEGRAM_ENABLE_DEFAULT="true"
    TELEGRAM_CONFIG_DIR_DEFAULT="$HOME/.TelegramDesktop"
    TELEGRAM_BINARY_DEFAULT="/opt/telegram/telegram"
    TELEGRAM_RESTART_COMMAND_DEFAULT=""

    TELEGRAM_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} telegram enable          2>/dev/null || echo "${TELEGRAM_ENABLE_DEFAULT}")"
    TELEGRAM_CONFIG_DIR="$(crudini      --get ${GCS_CONFIG_FILE} telegram config_file     2>/dev/null || echo "${TELEGRAM_CONFIG_DIR_DEFAULT}")"
    TELEGRAM_BINARY="$(crudini          --get ${GCS_CONFIG_FILE} telegram binary          2>/dev/null || echo "${TELEGRAM_BINARY_DEFAULT}")"
    TELEGRAM_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} telegram restart_command 2>/dev/null || echo "${TELEGRAM_RESTART_COMMAND_DEFAULT}")"
}



function check_dependencies() {
    if ! which "${TELEGRAM_BINARY}" >/dev/null; then
        return 1

    elif ! which zip >/dev/null; then
        return 1

    elif ! [ "${TELEGRAM_ENABLE}" == "true" ]; then
        printf "* Ignoring Telegram (disabled from configuration).\n"
        return 1

    elif ! [ -d "${TELEGRAM_CONFIG_DIR}" ]; then
        printf "* Ignoring Telegram (configuration directory \"${TELEGRAM_CONFIG_DIR}\" not found).\n"
        return 1

    else
        return 0

    fi
}



function derive_colors() {
    # basic colors
    : ${telegram_windowActiveTextFg=${link_color}}
    : ${telegram_windowBg:=${bg_color}}
    : ${telegram_windowBgActive=${link_color}}
    : ${telegram_windowBgOver=${selected_bg_color}}
    : ${telegram_windowBgRipple=${selected_fg_color}}
    : ${telegram_windowBoldFg=${fg_color}}
    : ${telegram_windowBoldFgOver=${selected_fg_color}}
    : ${telegram_windowFg:=${fg_color}}
    : ${telegram_windowFgActive=${selected_fg_color}}
    : ${telegram_windowFgOver=${selected_fg_color}}
    : ${telegram_windowShadowFg=${selected_bg_color}}
    : ${telegram_windowShadowFgFallback=${selected_bg_color}}
    : ${telegram_windowSubTextFg=${fg_color}}
    : ${telegram_windowSubTextFgOver=${fg_color}}

    # search box colors
    : ${telegram_filterInputActiveBg=${base_color}}
    : ${telegram_filterInputBorderFg=${link_color}}
    : ${telegram_filterInputInactiveBg=${base_color}}
    : ${telegram_searchedBarFg=${selected_fg_color}}

    # chat list colors
    : ${telegram_dialogsBgActive=${selected_bg_color}}
    : ${telegram_dialogsDateFg=${link_color}}
    : ${telegram_dialogsDateFgOver=${selected_fg_color}}
    : ${telegram_dialogsDraftFg=${link_color}}
    : ${telegram_dialogsDraftFgActive=${selected_fg_color}}
    : ${telegram_dialogsDraftFgOver=${selected_fg_color}}
    : ${telegram_dialogsSendingIconFg=${link_color}}
    : ${telegram_dialogsSendingIconFgActive=${selected_fg_color}}
    : ${telegram_dialogsSendingIconFgOver=${selected_fg_color}}
    : ${telegram_dialogsSentIconFg=${link_color}}
    : ${telegram_dialogsSentIconFgOver=${selected_fg_color}}
    : ${telegram_dialogsNameFgOver=${selected_fg_color}}
    : ${telegram_dialogsTextFgOver=${selected_fg_color}}
    : ${telegram_dialogsTextFgServiceOver=${selected_fg_color}}
    : ${telegram_dialogsUnreadBg=${selected_bg_color}}
    : ${telegram_dialogsUnreadBgOver=${selected_fg_color}}
    : ${telegram_dialogsUnreadBgMuted=${link_color}}
    : ${telegram_dialogsUnreadBgMutedOver=${selected_fg_color}}
    : ${telegram_dialogsUnreadFg=${selected_fg_color}}
    : ${telegram_dialogsUnreadFgOver=${selected_bg_color}}
    : ${telegram_dialogsVerifiedIconBg=${link_color}}
    : ${telegram_dialogsVerifiedIconBgOver=${selected_fg_color}}
    : ${telegram_dialogsVerifiedIconFgOver=${selected_bg_color}}

    # buttons colors
    : ${telegram_activeButtonBg=${selected_bg_color}}
    : ${telegram_activeButtonBgOver=${selected_bg_color}}
    : ${telegram_activeButtonBgRipple=${selected_fg_color}}
    : ${telegram_activeButtonFg=${selected_fg_color}}
    : ${telegram_activeButtonFgOver=${selected_fg_color}}
    : ${telegram_activeButtonSecondaryFg=${selected_fg_color}}
    : ${telegram_activeButtonSecondaryFgOver=${selected_fg_color}}
    : ${telegram_activeLineFg=${link_color}}
    : ${telegram_lightButtonBgOver=${selected_bg_color}}
    : ${telegram_lightButtonBgRipple=${selected_fg_color}}
    : ${telegram_lightButtonFgOver=${selected_fg_color}}
    : ${telegram_outlineButtonBgOver=${bg_color}}
    : ${telegram_outlineButtonBgRipple=${link_color}}

    # message colors
    : ${telegram_msgFileInBg=${link_color}}
    : ${telegram_msgFileInBgOver=${link_color}}
    : ${telegram_msgFileInBgSelected=${selected_fg_color}}
    : ${telegram_msgFileOutBg=${link_color}}
    : ${telegram_msgFileOutBgOver=${link_color}}
    : ${telegram_msgFileOutBgSelected=${selected_fg_color}}
    : ${telegram_msgFileThumbLinkOutFg=${link_color}}
    : ${telegram_msgFileThumbLinkOutFgSelected=${selected_fg_color}}
    : ${telegram_msgFile1Bg=${base0D}}
    : ${telegram_msgFile1BgDark="#00000033"}
    : ${telegram_msgFile1BgOver="#00000055"}
    : ${telegram_msgFile1BgSelected=${selected_fg_color}}
    : ${telegram_msgFile2Bg=${base0B}}
    : ${telegram_msgFile2BgDark="#00000033"}
    : ${telegram_msgFile2BgOver="#00000055"}
    : ${telegram_msgFile2BgSelected=${selected_fg_color}}
    : ${telegram_msgFile3Bg=${base08}}
    : ${telegram_msgFile3BgDark="#00000033"}
    : ${telegram_msgFile3BgOver="#00000055"}
    : ${telegram_msgFile3BgSelected=${selected_fg_color}}
    : ${telegram_msgFile4Bg=${base0A}}
    : ${telegram_msgFile4BgDark="#00000033"}
    : ${telegram_msgFile4BgOver="#00000055"}
    : ${telegram_msgFile4BgSelected=${selected_fg_color}}
    : ${telegram_msgImgReplyBarColor=${selected_fg_color}}
    : ${telegram_msgInBg=${notification_bg_color}}
    : ${telegram_msgInBgSelected=${selected_bg_color}}
    : ${telegram_msgInDateFg=${link_color}}
    : ${telegram_msgInDateFgSelected=${selected_fg_color}}
    : ${telegram_msgInMonoFg=${notification_fg_color}}
    : ${telegram_msgInMonoFgSelected=${selected_fg_color}}
    : ${telegram_msgInShadow=${link_color}88}
    : ${telegram_msgInServiceFgSelected=${selected_fg_color}}
    : ${telegram_msgOutBg=${base_color}}
    : ${telegram_msgOutBgSelected=${selected_bg_color}}
    : ${telegram_msgOutDateFg=${link_color}}
    : ${telegram_msgOutDateFgSelected=${selected_fg_color}}
    : ${telegram_msgOutMonoFg=${text_color}}
    : ${telegram_msgOutMonoFgSelected=${selected_fg_color}}
    : ${telegram_msgOutReplyBarSelColor=${selected_fg_color}}
    : ${telegram_msgOutShadow=${link_color}88}
    : ${telegram_msgOutServiceFg=${link_color}}
    : ${telegram_msgOutServiceFgSelected=${selected_fg_color}}
    : ${telegram_msgSelectOverlay=${selected_bg_color}88}
    : ${telegram_msgServiceBg=${link_color}88}
    : ${telegram_msgServiceBgSelected=${link_color}}
    : ${telegram_msgStickerOverlay=${selected_bg_color}88}
    : ${telegram_msgWaveformInActive=${link_color}}
    : ${telegram_msgWaveformInActiveSelected=${selected_fg_color}}
    : ${telegram_msgWaveformInInactive=${notification_fg_color}}
    : ${telegram_msgWaveformInInactiveSelected=${selected_fg_color}88}
    : ${telegram_msgWaveformOutActive=${link_color}}
    : ${telegram_msgWaveformOutActiveSelected=${selected_fg_color}}
    : ${telegram_msgWaveformOutInactive=${fg_color}}
    : ${telegram_msgWaveformOutInactiveSelected=${selected_fg_color}88}
    : ${telegram_historyComposeAreaBg=${bg_color}}
    : ${telegram_historyFileNameInFgSelected=${selected_fg_color}}
    : ${telegram_historyFileNameOutFgSelected=${selected_fg_color}}
    : ${telegram_historyLinkInFg=${link_color}}
    : ${telegram_historyLinkInFgSelected=${selected_fg_color}}
    : ${telegram_historyLinkOutFgSelected=${selected_fg_color}}
    : ${telegram_historyOutIconFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer1NameFg=${base08}}
    : ${telegram_historyPeer1UserpicBg=${base08}}
    : ${telegram_historyPeer1NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer2NameFg=${base0B}}
    : ${telegram_historyPeer2UserpicBg=${base0B}}
    : ${telegram_historyPeer2NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer3NameFg=${base0A}}
    : ${telegram_historyPeer3UserpicBg=${base0A}}
    : ${telegram_historyPeer3NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer4NameFg=${base0D}}
    : ${telegram_historyPeer4UserpicBg=${base0D}}
    : ${telegram_historyPeer4NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer5NameFg=${base0E}}
    : ${telegram_historyPeer5UserpicBg=${base0E}}
    : ${telegram_historyPeer5NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer6NameFg=${base0F}}
    : ${telegram_historyPeer6UserpicBg=${base0F}}
    : ${telegram_historyPeer6NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer7NameFg=${base0C}}
    : ${telegram_historyPeer7UserpicBg=${base0C}}
    : ${telegram_historyPeer7NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer8NameFg=${base09}}
    : ${telegram_historyPeer8UserpicBg=${base09}}
    : ${telegram_historyPeer8NameFgSelected=${selected_fg_color}}
    : ${telegram_historyPeer9NameFgSelected=${selected_fg_color}}
    : ${telegram_historyTextInFg=${notification_fg_color}}
    : ${telegram_historyTextInFgSelected=${selected_fg_color}}
    : ${telegram_historyTextOutFg=${text_color}}
    : ${telegram_historyTextOutFgSelected=${selected_fg_color}}
    : ${telegram_historyToDownShadow=${link_color}88}

    # icons colors
    : ${telegram_cancelIconFgOver=${link_color}}
    : ${telegram_dialogsMenuIconFgOver=${link_color}}
    : ${telegram_historyComposeIconFgOver=${link_color}}
    : ${telegram_historySendIconFg=${fg_color}}
    : ${telegram_historySendIconFgOver=${link_color}}
    : ${telegram_historySendingInIconFg=${link_color}}
    : ${telegram_historySendingOutIconFg=${link_color}}
    : ${telegram_historyReplyIconFg=${link_color}}
    : ${telegram_historyToDownFgOver=${selected_fg_color}}
    : ${telegram_mainMenuCloudBg=${selected_fg_color}}
    : ${telegram_mainMenuCloudFg=${selected_bg_color}}
    : ${telegram_menuIconFg=${fg_color}}
    : ${telegram_menuIconFgOver=${selected_fg_color}}
    : ${telegram_emojiIconFg=${fg_color}}
    : ${telegram_emojiIconFgActive=${link_color}}

    # tooltip colors
    : ${telegram_tooltipBg=${tooltip_bg_color}}
    : ${telegram_tooltipBorderFg=${tooltip_border_color}}
    : ${telegram_tooltipFg=${tooltip_fg_color}}

    # scrollbars colors
    : ${telegram_scrollBarBg=${link_color}}
    : ${telegram_scrollBarBgOver=${selected_bg_color}}
    : ${telegram_scrollBg=${base_color}}
    : ${telegram_scrollBgOver=${base_color}}
    : ${telegram_historyScrollBarBg=${link_color}}
    : ${telegram_historyScrollBarBgOver=${selected_bg_color}}
    : ${telegram_historyScrollBg=${bg_color}}
    : ${telegram_historyScrollBgOver=${bg_color}}
    : ${telegram_historyUnreadBarBg=${selected_bg_color}}
    : ${telegram_historyUnreadBarFg=${selected_fg_color}}

    # other
    : ${telegram_boxTitleFg=${fg_color}}
    : ${telegram_menuSeparatorFg=${selected_bg_color}}
}



function create_backup() {
    printf "* Backup/restore not supported with Telegram.\n"
}



function restore_backup() {
    printf "* Backup/restore not supported with Telegram.\n"
}



function dry_run() {
    printf "* Telegram: create a new theme in \"${TELEGRAM_CONFIG_DIR}/gcs.tdesktop-theme\".\n"
}



function apply_theme() {
    printf "* Setting colors for Telegram..."
    
    TELEGRAM_TMP_DIR="${GCS_TMP_DIR}/telegram"
    mkdir "${TELEGRAM_TMP_DIR}"
    TELEGRAM_PALETTE_FILE="${TELEGRAM_TMP_DIR}/colors.tdesktop-theme"
    touch "${TELEGRAM_PALETTE_FILE}"
    TELEGRAM_THEME_FILE="${TELEGRAM_CONFIG_DIR}/gcs.tdesktop-theme"

    set_value "windowActiveTextFg"     ": " "${telegram_windowActiveTextFg};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "windowBg"               ": " "${telegram_windowBg};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "windowBgActive"         ": " "${telegram_windowBgActive};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "windowBgOver"           ": " "${telegram_windowBgOver};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "windowBgRipple"         ": " "${telegram_windowBgRipple};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "windowBoldFg"           ": " "${telegram_windowBoldFg};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "windowBoldFgOver"       ": " "${telegram_windowBoldFgOver};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "windowFg"               ": " "${telegram_windowFg};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "windowFgActive"         ": " "${telegram_windowFgActive};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "windowFgOver"           ": " "${telegram_windowFgOver};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "windowShadowFg"         ": " "${telegram_windowShadowFg};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "windowShadowFgFallback" ": " "${telegram_windowShadowFgFallback};" "${TELEGRAM_PALETTE_FILE}"
    set_value "windowSubTextFg"        ": " "${telegram_windowSubTextFg};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "windowSubTextFgOver"    ": " "${telegram_windowSubTextFgOver};"    "${TELEGRAM_PALETTE_FILE}"

    set_value "filterInputActiveBg"   ": " "${telegram_filterInputActiveBg};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "filterInputBorderFg"   ": " "${telegram_filterInputBorderFg};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "filterInputInactiveBg" ": " "${telegram_filterInputInactiveBg};" "${TELEGRAM_PALETTE_FILE}"
    set_value "searchedBarFg"         ": " "${telegram_searchedBarFg};"         "${TELEGRAM_PALETTE_FILE}"

    set_value "dialogsBgActive"            ": " "${telegram_dialogsBgActive};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsDateFg"              ": " "${telegram_dialogsDateFg};"              "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsDateFgOver"          ": " "${telegram_dialogsDateFgOver};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsDraftFg"             ": " "${telegram_dialogsDraftFg};"             "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsDraftFgActive"       ": " "${telegram_dialogsDraftFgActive};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsDraftFgOver"         ": " "${telegram_dialogsDraftFgOver};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsSendingIconFg"       ": " "${telegram_dialogsSendingIconFg};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsSendingIconFgActive" ": " "${telegram_dialogsSendingIconFgActive};" "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsSendingIconFgOver"   ": " "${telegram_dialogsSendingIconFgOver};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsSentIconFg"          ": " "${telegram_dialogsSentIconFg};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsSentIconFgOver"      ": " "${telegram_dialogsSentIconFgOver};"      "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsNameFgOver"          ": " "${telegram_dialogsNameFgOver};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsTextFgOver"          ": " "${telegram_dialogsTextFgOver};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsTextFgServiceOver"   ": " "${telegram_dialogsTextFgServiceOver};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsUnreadBg"            ": " "${telegram_dialogsUnreadBg};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsUnreadBgOver"        ": " "${telegram_dialogsUnreadBgOver};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsUnreadBgMuted"       ": " "${telegram_dialogsUnreadBgMuted};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsUnreadBgMutedOver"   ": " "${telegram_dialogsUnreadBgMutedOver};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsUnreadFg"            ": " "${telegram_dialogsUnreadFg};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsUnreadFgOver"        ": " "${telegram_dialogsUnreadFgOver};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsVerifiedIconBg"      ": " "${telegram_dialogsVerifiedIconBg};"      "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsVerifiedIconBgOver"  ": " "${telegram_dialogsVerifiedIconBgOver};"  "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsVerifiedIconFgOver"  ": " "${telegram_dialogsVerifiedIconFgOver};"  "${TELEGRAM_PALETTE_FILE}"

    set_value "activeButtonBg"              ": " "${telegram_activeButtonBg};"              "${TELEGRAM_PALETTE_FILE}"
    set_value "activeButtonBgOver"          ": " "${telegram_activeButtonBgOver};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "activeButtonBgRipple"        ": " "${telegram_activeButtonBgRipple};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "activeButtonFg"              ": " "${telegram_activeButtonFg};"              "${TELEGRAM_PALETTE_FILE}"
    set_value "activeButtonFgOver"          ": " "${telegram_activeButtonFgOver};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "activeButtonSecondaryFg"     ": " "${telegram_activeButtonSecondaryFg};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "activeButtonSecondaryFgOver" ": " "${telegram_activeButtonSecondaryFgOver};" "${TELEGRAM_PALETTE_FILE}"
    set_value "activeLineFg"                ": " "${telegram_activeLineFg};"                "${TELEGRAM_PALETTE_FILE}"
    set_value "lightButtonBgOver"           ": " "${telegram_lightButtonBgOver};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "lightButtonBgRipple"         ": " "${telegram_lightButtonBgRipple};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "lightButtonFgOver"           ": " "${telegram_lightButtonFgOver};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "outlineButtonBgOver"         ": " "${telegram_outlineButtonBgOver};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "outlineButtonBgRipple"       ": " "${telegram_outlineButtonBgRipple};"       "${TELEGRAM_PALETTE_FILE}"

    set_value "msgFileInBg"                    ": " "${telegram_msgFileInBg};"                    "${TELEGRAM_PALETTE_FILE}"
    set_value "msgFileInBgOver"                ": " "${telegram_msgFileInBgOver};"                "${TELEGRAM_PALETTE_FILE}"
    set_value "msgFileInBgSelected"            ": " "${telegram_msgFileInBgSelected};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "msgFileOutBg"                   ": " "${telegram_msgFileOutBg};"                   "${TELEGRAM_PALETTE_FILE}"
    set_value "msgFileOutBgOver"               ": " "${telegram_msgFileOutBgOver};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "msgFileOutBgSelected"           ": " "${telegram_msgFileOutBgSelected};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "msgFileThumbLinkOutFg"          ": " "${telegram_msgFileThumbLinkOutFg};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "msgFileThumbLinkOutFgSelected"  ": " "${telegram_msgFileThumbLinkOutFgSelected};"  "${TELEGRAM_PALETTE_FILE}"
    set_value "msgImgReplyBarColor"            ": " "${telegram_msgImgReplyBarColor};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInBg"                        ": " "${telegram_msgInBg};"                        "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInBgSelected"                ": " "${telegram_msgInBgSelected};"                "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInDateFg"                    ": " "${telegram_msgInDateFg};"                    "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInDateFgSelected"            ": " "${telegram_msgInDateFgSelected};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "historyTextInFg"                ": " "${telegram_historyTextInFg};"                "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInMonoFg"                    ": " "${telegram_msgInMonoFg};"                    "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInMonoFgSelected"            ": " "${telegram_msgInMonoFgSelected};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInShadow"                    ": " "${telegram_msgInShadow};"                    "${TELEGRAM_PALETTE_FILE}"
    set_value "msgInServiceFgSelected"         ": " "${telegram_msgInServiceFgSelected};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutBg"                       ": " "${telegram_msgOutBg};"                       "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutBgSelected"               ": " "${telegram_msgOutBgSelected};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutDateFg"                   ": " "${telegram_msgOutDateFg};"                   "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutDateFgSelected"           ": " "${telegram_msgOutDateFgSelected};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "historyTextOutFg"               ": " "${telegram_historyTextOutFg};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutMonoFg"                   ": " "${telegram_msgOutMonoFg};"                   "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutMonoFgSelected"           ": " "${telegram_msgOutMonoFgSelected};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutReplyBarSelColor"         ": " "${telegram_msgOutReplyBarSelColor};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutShadow"                   ": " "${telegram_msgOutShadow};"                   "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutServiceFg"                ": " "${telegram_msgOutServiceFg};"                "${TELEGRAM_PALETTE_FILE}"
    set_value "msgOutServiceFgSelected"        ": " "${telegram_msgOutServiceFgSelected};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "msgSelectOverlay"               ": " "${telegram_msgSelectOverlay};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "msgServiceBg"                   ": " "${telegram_msgServiceBg};"                   "${TELEGRAM_PALETTE_FILE}"
    set_value "msgServiceBgSelected"           ": " "${telegram_msgServiceBgSelected};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "msgStickerOverlay"              ": " "${telegram_msgStickerOverlay};"              "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformInActive"            ": " "${telegram_msgWaveformInActive};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformInActiveSelected"    ": " "${telegram_msgWaveformInActiveSelected};"    "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformInInactive"          ": " "${telegram_msgWaveformInInactive};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformInInactiveSelected"  ": " "${telegram_msgWaveformInInactiveSelected};"  "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformOutActive"           ": " "${telegram_msgWaveformOutActive};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformOutActiveSelected"   ": " "${telegram_msgWaveformOutActiveSelected};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformOutInactive"         ": " "${telegram_msgWaveformOutInactive};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "msgWaveformOutInactiveSelected" ": " "${telegram_msgWaveformOutInactiveSelected};" "${TELEGRAM_PALETTE_FILE}"
    set_value "historyComposeAreaBg"           ": " "${telegram_historyComposeAreaBg};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "historyFileNameInFgSelected"    ": " "${telegram_historyFileNameInFgSelected};"    "${TELEGRAM_PALETTE_FILE}"
    set_value "historyFileNameOutFgSelected"   ": " "${telegram_historyFileNameOutFgSelected};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "historyLinkInFg"                ": " "${telegram_historyLinkInFg};"                "${TELEGRAM_PALETTE_FILE}"
    set_value "historyLinkInFgSelected"        ": " "${telegram_historyLinkInFgSelected};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "historyLinkOutFgSelected"       ": " "${telegram_historyLinkOutFgSelected};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "historyOutIconFgSelected"       ": " "${telegram_historyOutIconFgSelected};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer1NameFgSelected"     ": " "${telegram_historyPeer1NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer2NameFgSelected"     ": " "${telegram_historyPeer2NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer3NameFgSelected"     ": " "${telegram_historyPeer3NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer4NameFgSelected"     ": " "${telegram_historyPeer4NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer5NameFgSelected"     ": " "${telegram_historyPeer5NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer6NameFgSelected"     ": " "${telegram_historyPeer6NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer7NameFgSelected"     ": " "${telegram_historyPeer7NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer8NameFgSelected"     ": " "${telegram_historyPeer8NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyPeer9NameFgSelected"     ": " "${telegram_historyPeer9NameFgSelected};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyTextInFgSelected"        ": " "${telegram_historyTextInFgSelected};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "historyTextOutFgSelected"       ": " "${telegram_historyTextOutFgSelected};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "historyToDownShadow"            ": " "${telegram_historyToDownShadow};"            "${TELEGRAM_PALETTE_FILE}"

    [ -z "${telegram_msgFile1Bg}" ] || set_value "msgFile1Bg"         ": " "${telegram_msgFile1Bg};"         "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile1Bg}" ] || set_value "msgFile1BgDark"     ": " "${telegram_msgFile1BgDark};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile1Bg}" ] || set_value "msgFile1BgOver"     ": " "${telegram_msgFile1BgOver};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile1Bg}" ] || set_value "msgFile1BgSelected" ": " "${telegram_msgFile1BgSelected};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile2Bg}" ] || set_value "msgFile2Bg"         ": " "${telegram_msgFile2Bg};"         "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile2Bg}" ] || set_value "msgFile2BgDark"     ": " "${telegram_msgFile2BgDark};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile2Bg}" ] || set_value "msgFile2BgOver"     ": " "${telegram_msgFile2BgOver};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile2Bg}" ] || set_value "msgFile2BgSelected" ": " "${telegram_msgFile2BgSelected};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile3Bg}" ] || set_value "msgFile3Bg"         ": " "${telegram_msgFile3Bg};"         "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile3Bg}" ] || set_value "msgFile3BgDark"     ": " "${telegram_msgFile3BgDark};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile3Bg}" ] || set_value "msgFile3BgOver"     ": " "${telegram_msgFile3BgOver};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile3Bg}" ] || set_value "msgFile3BgSelected" ": " "${telegram_msgFile3BgSelected};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile4Bg}" ] || set_value "msgFile4Bg"         ": " "${telegram_msgFile4Bg};"         "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile4Bg}" ] || set_value "msgFile4BgDark"     ": " "${telegram_msgFile4BgDark};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile4Bg}" ] || set_value "msgFile4BgOver"     ": " "${telegram_msgFile4BgOver};"     "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_msgFile4Bg}" ] || set_value "msgFile4BgSelected" ": " "${telegram_msgFile4BgSelected};" "${TELEGRAM_PALETTE_FILE}"

    [ -z "${telegram_historyPeer1NameFg}"    ] || set_value "historyPeer1NameFg"    ": " "${telegram_historyPeer1NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer1UserpicBg}" ] || set_value "historyPeer1UserpicBg" ": " "${telegram_historyPeer1UserpicBg};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer2NameFg}"    ] || set_value "historyPeer2NameFg"    ": " "${telegram_historyPeer2NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer2UserpicBg}" ] || set_value "historyPeer2UserpicBg" ": " "${telegram_historyPeer2UserpicBg};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer3NameFg}"    ] || set_value "historyPeer3NameFg"    ": " "${telegram_historyPeer3NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer3UserpicBg}" ] || set_value "historyPeer3UserpicBg" ": " "${telegram_historyPeer3UserpicBg};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer4NameFg}"    ] || set_value "historyPeer4NameFg"    ": " "${telegram_historyPeer4NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer4UserpicBg}" ] || set_value "historyPeer4UserpicBg" ": " "${telegram_historyPeer4UserpicBg};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer5NameFg}"    ] || set_value "historyPeer5NameFg"    ": " "${telegram_historyPeer5NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer5UserpicBg}" ] || set_value "historyPeer5UserpicBg" ": " "${telegram_historyPeer5UserpicBg};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer6NameFg}"    ] || set_value "historyPeer6NameFg"    ": " "${telegram_historyPeer6NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer6UserpicBg}" ] || set_value "historyPeer6UserpicBg" ": " "${telegram_historyPeer6UserpicBg};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer7NameFg}"    ] || set_value "historyPeer7NameFg"    ": " "${telegram_historyPeer7NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer7UserpicBg}" ] || set_value "historyPeer7UserpicBg" ": " "${telegram_historyPeer7UserpicBg};" "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer8NameFg}"    ] || set_value "historyPeer8NameFg"    ": " "${telegram_historyPeer8NameFg};"    "${TELEGRAM_PALETTE_FILE}"
    [ -z "${telegram_historyPeer8UserpicBg}" ] || set_value "historyPeer8UserpicBg" ": " "${telegram_historyPeer8UserpicBg};" "${TELEGRAM_PALETTE_FILE}"

    set_value "cancelIconFgOver"         ": " "${telegram_cancelIconFgOver};"         "${TELEGRAM_PALETTE_FILE}"
    set_value "dialogsMenuIconFgOver"    ": " "${telegram_dialogsMenuIconFgOver};"    "${TELEGRAM_PALETTE_FILE}"
    set_value "historyComposeIconFgOver" ": " "${telegram_historyComposeIconFgOver};" "${TELEGRAM_PALETTE_FILE}"
    set_value "historySendIconFg"        ": " "${telegram_historySendIconFg};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "historySendIconFgOver"    ": " "${telegram_historySendIconFgOver};"    "${TELEGRAM_PALETTE_FILE}"
    set_value "historySendingInIconFg"   ": " "${telegram_historySendingInIconFg};"   "${TELEGRAM_PALETTE_FILE}"
    set_value "historySendingOutIconFg"  ": " "${telegram_historySendingOutIconFg};"  "${TELEGRAM_PALETTE_FILE}"
    set_value "historyReplyIconFg"       ": " "${telegram_historyReplyIconFg};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "historyToDownFgOver"      ": " "${telegram_historyToDownFgOver};"      "${TELEGRAM_PALETTE_FILE}"
    set_value "mainMenuCloudBg"          ": " "${telegram_mainMenuCloudBg};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "mainMenuCloudFg"          ": " "${telegram_mainMenuCloudFg};"          "${TELEGRAM_PALETTE_FILE}"
    set_value "menuIconFg"               ": " "${telegram_menuIconFg};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "menuIconFgOver"           ": " "${telegram_menuIconFgOver};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "emojiIconFg"              ": " "${telegram_emojiIconFg};"              "${TELEGRAM_PALETTE_FILE}"
    set_value "emojiIconFgActive"        ": " "${telegram_emojiIconFgActive};"        "${TELEGRAM_PALETTE_FILE}"

    set_value "tooltipBg"       ": " "${telegram_tooltipBg};"       "${TELEGRAM_PALETTE_FILE}"
    set_value "tooltipBorderFg" ": " "${telegram_tooltipBorderFg};" "${TELEGRAM_PALETTE_FILE}"
    set_value "tooltipFg"       ": " "${telegram_tooltipFg};"       "${TELEGRAM_PALETTE_FILE}"

    set_value "scrollBarBg"            ": " "${telegram_scrollBarBg};"            "${TELEGRAM_PALETTE_FILE}"
    set_value "scrollBarBgOver"        ": " "${telegram_scrollBarBgOver};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "scrollBg"               ": " "${telegram_scrollBg};"               "${TELEGRAM_PALETTE_FILE}"
    set_value "scrollBgOver"           ": " "${telegram_scrollBgOver};"           "${TELEGRAM_PALETTE_FILE}"
    set_value "historyScrollBarBg"     ": " "${telegram_historyScrollBarBg};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyScrollBarBgOver" ": " "${telegram_historyScrollBarBgOver};" "${TELEGRAM_PALETTE_FILE}"
    set_value "historyScrollBg"        ": " "${telegram_historyScrollBg};"        "${TELEGRAM_PALETTE_FILE}"
    set_value "historyScrollBgOver"    ": " "${telegram_historyScrollBgOver};"    "${TELEGRAM_PALETTE_FILE}"
    set_value "historyUnreadBarBg"     ": " "${telegram_historyUnreadBarBg};"     "${TELEGRAM_PALETTE_FILE}"
    set_value "historyUnreadBarFg"     ": " "${telegram_historyUnreadBarFg};"     "${TELEGRAM_PALETTE_FILE}"

    set_value "boxTitleFg"      ": " "${telegram_boxTitleFg};"      "${TELEGRAM_PALETTE_FILE}"
    set_value "menuSeparatorFg" ": " "${telegram_menuSeparatorFg};" "${TELEGRAM_PALETTE_FILE}"



    for i in ${COLOR_THEME_DIRS[@]}; do
        if [ -f "$i/${wallpaper_image}" ]; then
            wallpaper_file="$i/${wallpaper_image}"
        fi
    done

    if [ -f "${wallpaper_file}" ]; then
        if [ "${wallpaper_mode}" == "tiled" ]; then
            TELEGRAM_WALLPAPER_FILE="${TELEGRAM_TMP_DIR}/tiled.${wallpaper_file##*.}"
        else
            TELEGRAM_WALLPAPER_FILE="${TELEGRAM_TMP_DIR}/background.${wallpaper_file##*.}"
        fi
        cp "${wallpaper_file}" "${TELEGRAM_WALLPAPER_FILE}"
        [ -f "${TELEGRAM_THEME_FILE}" ] && rm "${TELEGRAM_THEME_FILE}"
        zip -j "${TELEGRAM_THEME_FILE}" "${TELEGRAM_PALETTE_FILE}" "${TELEGRAM_WALLPAPER_FILE}" &>/dev/null
    else
        mv "${TELEGRAM_PALETTE_FILE}" "${TELEGRAM_THEME_FILE}"
    fi

    eval ${TELEGRAM_RESTART_COMMAND} &>/dev/null

    printf " done.\n"
}

