#!/bin/sh

# TODO: handle profiles
# TODO: set color palette
# TODO: use set_value when sections and initial whitespaces are handled

TERMINATOR_CONFIG_FILE="$HOME/.config/terminator/config"
if [ -f "${TERMINATOR_CONFIG_FILE}" ]; then
    echo "* setting colors for terminator..."
    sed -i "s/background_color =.*/background_color = \"${terminal_bg_color}\"/" "${TERMINATOR_CONFIG_FILE}"
    sed -i "s/cursor_color =.*/cursor_color = \"${terminal_fg_color}\"/" "${TERMINATOR_CONFIG_FILE}"
    sed -i "s/foreground_color =.*/foreground_color = \"${terminal_fg_color}\"/" "${TERMINATOR_CONFIG_FILE}"
    echo "  Done."
fi
