#!/bin/bash

WINMENU_FILE="$HOME/bin/winmenu.py"
if [ -f "${WINMENU_FILE}" ]; then

    printf "* Setting colors for winmenu.py..."
    
    set_value "normal_background"   " = " "\"${bg_color}\""          "${WINMENU_FILE}"
    set_value "normal_foreground"   " = " "\"${fg_color}\""          "${WINMENU_FILE}"
    set_value "selected_background" " = " "\"${selected_bg_color}\"" "${WINMENU_FILE}"
    set_value "selected_foreground" " = " "\"${selected_bg_color}\"" "${WINMENU_FILE}"
    
    printf " done.\n"
    
fi
