#!/bin/bash

which xfce4-notifyd-config >/dev/null || return

XFCE4_NOTIFYD_ENABLE_DEFAULT="true"
XFCE4_NOTIFYD_RESTART_COMMAND_DEFAULT="killall xfce4-notifyd"

XFCE4_NOTIFYD_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} xfce4_notifyd enable          2>/dev/null || echo "${XFCE4_NOTIFYD_ENABLE_DEFAULT}")"
XFCE4_NOTIFYD_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} xfce4_notifyd restart_command 2>/dev/null || echo "${XFCE4_NOTIFYD_RESTART_COMMAND_DEFAULT}")"

: ${xfce4_notifyd_border_color:=${notification_border_color}}
: ${xfce4_notifyd_bg_color:=${notification_bg_color}}
: ${xfce4_notifyd_fg_color:=${notification_fg_color}}

if ! [ "${XFCE4_NOTIFYD_ENABLE}" == "true" ]; then
    printf "* Not setting colors for xfce4-notifyd (disabled from configuration).\n"

else
    printf "* Setting colors for xfce4-notifyd..."
    mkdir -p "${HOME}/.themes/gcs-theme/xfce-notify-4.0"
    echo "
#XfceNotifyWindow {
    background-color: ${xfce4_notifyd_bg_color};
    color: ${xfce4_notifyd_fg_color};
    border: 1px solid ${xfce4_notifyd_border_color};
}

#XfceNotifyWindow label#summary {
    font-weight: Bold;
}
" > "${HOME}/.themes/gcs-theme/xfce-notify-4.0/gtk.css"
    xfconf-query -c xfce4-notifyd -p /theme -s "gcs-theme"

    $XFCE4_NOTIFYD_RESTART_COMMAND &>/dev/null
    printf " done.\n"
fi
