#!/bin/bash

# GCS - Global Color Scheme
#
# Copyright (C) 2015 Livanh <livanh@bulletmail.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# TODO: enable or disable modules with a config file
# TODO: create per-module configuration in config files
# TODO: look for modules and themes in both system and user-specific directories
# TODO: show a list of available color schemes when running without arguments 

MODULES_DIR="$HOME/.local/share/gcs/modules"
CONFIG_DIR="$HOME/.config/gcs"
THEMES_DIR="$HOME/.config/gcs/colorthemes"

if [ "$#" -ne 1 ]; then
    echo Usage: $0 \<color theme name\>
    exit 1
fi
COLOR_THEME="$1"

if [ -f "${THEMES_DIR}/${COLOR_THEME}/colortheme" ]; then
    echo "Applying color theme ${COLOR_THEME}"
    echo
    for i in "${MODULES_DIR}/"*; do
	if [ -x "$i" ]; then
	    . "${THEMES_DIR}/${COLOR_THEME}/colortheme"
	    . "$i"
	    echo
	fi
    done
else
    echo Error: theme ${COLOR_THEME} not found!
    exit 2
fi
